### PR TITLE
[SMALLFIX] Rename properties for integration module

### PR DESCRIPTION
**Pull request by apc999**

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by yupeng9** [comment]
Shall we update the docs accordingly?

**Comment by apc999** [comment]
@yupeng9 currently they have no documentation in configuration-setting.md. So if this PR gets merged, I will either add doc into 0.8-docs (if it is still open), or directly submit PR to modify the md file in master

**Comment by yupeng9** [comment]
SGTM

**Comment by yupeng9** [comment]
+1

**Pull request merged**
