### PR TITLE
[TACHYON-737] Deploy release with correct Hadoop version

### PR DESCRIPTION
**Pull request by danielfree**
https://tachyon.atlassian.net/browse/TACHYON-737

Tachyon download_release task and script are modified to determine which tachyon binary to download based on the user's understorage options. If the targeted binary release is not available, the ansible playbook will fail and display error msg guiding the user to use tachyon github type with a proper branch.

### CODE REVIEW

**Comment by danielfree** [comment]
jenkins, test this please

**Comment by uronce-cc** [comment]
@danielfree I just reviewed [a very similar PR](https://github.com/amplab/tachyon/pull/1474), its approach is to determine tachyon release version when initializing vagrant environment, I feel this approach can find out version in compatibility earlier than detecting the incompatibility when executing playbook. What do you think about?

**Comment by danielfree** [comment]
@uronce-cc Oops, I didn't notice that PR before:(  I'm not familiar with ruby so I take this approach, and I think determining version in vagrant setup seems reasonable, just a few suggestions: 

Detecting version starts with 2.4/2.6 will not be compatible with newer hadoop releases. Instead the way in the modified download_release.sh is more flexible using ```echo $HADOOP_VERSION | cut -d'.' -f1,2```, which will not break if we have newer hadoop build in the future (lastest hadoop release is 2.7.1).

Another aspect is that we may go ahead to compile the base binary release if we don't find a proper build. I can figure out a way to do this with ansible&scipt, so I guess it's the same with vagrant setup approach. Great work https://github.com/amplab/tachyon/pull/1474 !

**Comment by calvinjia** [comment]
@danielfree do you want to change this PR to improve the implementation in #1474 with your suggestions? Or we can just close the PR and open another ticket.

**Comment by danielfree** [comment]
@calvinjia let's just close this PR and open another one if we want to improve it. For now I think #1474 is sufficient.

**Comment by calvinjia** [comment]
@danielfree Sure.

**Pull request closed without merging**
