### PR TITLE
[TACHYON-981] removed reduntant final for private methods

### PR DESCRIPTION
**Pull request by ptonpay**
JIRA Ticket - [TACHYON-981]
https://tachyon.atlassian.net/browse/TACHYON-981

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Could you rename the PR so that it has the jira ticket, like "[TACHYON-XXXX] ..."? Also, it would be nice to have a link to the jira ticket in the description. Thanks!

**Comment by ptonpay** [comment]
Hi, i renamed the PR as suggested by Gene Pang... i am new to this, so was
not aware....

thx
pranay

**Comment by calvinjia** [comment]
@ptonpay Could you resolve the merge conflicts please?

**Comment by miasantreble** [comment]
LGTM
@ptonpay , can you please update your initial comment in this pull request to include the link to the JIRA? 
Similar to this pull request: https://github.com/amplab/tachyon/pull/1652
It would help reviewers quickly get back to the original JIRA to collect some background information. 
Thanks!

**Comment by ptonpay** [comment]
just did that ,,, pls check

thx

**Comment by miasantreble** [comment]
@ptonpay thanks for the update. Can you please rebase from master to resolve the merge conflicts?

**Comment by ptonpay** [comment]
hi ... i am not sure what i am missing,, but git status doesnt show me any
conflicts... ( i have been using cvs and svn, so git is a little new to me
)... can u pls advise...

**Comment by miasantreble** [comment]
@ptonpay what you can do is the following
git checkout master
git pull
git checkout $YOUR_BRANCH
git rebase -i master
... build, unit test, etc.  commit any fixes ...
git push origin $YOUR_BRANCH

**Comment by ptonpay** [comment]
hi ... i just didt that .. can u please verify... sorry, for the delay, but
being new to git, i am learning it

**Comment by miasantreble** [comment]
@ptonpay I think your git push origin $YOUR_BRANCH failed?
you might want to do git push -f origin $YOUR_BRANCH

**Comment by ptonpay** [comment]
just did that and it said "Everything upto date" ...

**Comment by calvinjia** [comment]
@ptonpay you may want to take a look at the git forking guide: https://help.github.com/articles/fork-a-repo/. The keeping your fork synced portion should be helpful.

**Comment by ptonpay** [comment]
hi ... do u still see an issue with this ? or am i done from my side ?
how do i mark it as "REsolved" if it okay to do it ? From the browser, i am
unable to ...

kindly opine.

**Comment by calvinjia** [comment]
@ptonpay the merge conflicts are still not resolved, meaning the line of code being modified has changed in the master branch between the time you first checked out the branch and now, try using the guide I linked above.

**Comment by ptonpay** [comment]
okay, so i undid my changes, checkout fresh and made that change again and
pushed it.... i suppose this should have done it this time ... pls let me
know

**Comment by apc999** [comment]
Close this PR as PR #1675 is based on same commits from here with conflict resolved.

**Comment by ptonpay** [comment]
after checking in the code .. how do i mark the issue as resolved ?

**Comment by apc999** [comment]
@ptonpay , I have closed the issue on JIRA---new users can take JIRA tasks but not close them.
Thanks for the patch!

**Comment by ptonpay** [comment]
i have fixed TACHYON-1082
<https://tachyon.atlassian.net/browse/TACHYON-1082> as well... can u please
do the needful ?

**Pull request closed without merging**
