### PR TITLE
[TACHYON-1675] Fix a ssh problem when deploying EC2 with Vagrant.

### PR DESCRIPTION
**Pull request by ifcharming**
https://tachyon.atlassian.net/browse/TACHYON-1675

EC2 instance DNS name length can exceed Unix socket size limit, causing ssh error.
http://docs.ansible.com/ansible/intro_configuration.html#control-path

### CODE REVIEW

**Comment by jsimsa** [comment]
LGTM

**Comment by apc999** [comment]
+1 LGTM

**Comment by aaudiber** [comment]
LGTM

**Comment by uronce-cc** [comment]
LGTM ++

**Comment by uronce-cc** [comment]
I'd like to add a link to http://docs.ansible.com/ansible/intro_configuration.html#control-path

**Comment by ifcharming** [comment]
Updated, thanks CC.

**Comment by apc999** [comment]
@ifcharming the repo is not updated (you mentioned the link)

**Comment by ifcharming** [comment]
Actually adding the link in the code comment. Thanks Bin.

**Comment by apc999** [comment]
+1 LGTM

**Pull request merged**
