### PR TITLE
[SMALLFIX] close resource in test

### PR DESCRIPTION
**Pull request by aaudiber**

### CODE REVIEW

**Comment by apc999** [comment]
@aaudiber , the try-with-resources statement is supported by Java 7 or later. Currently Tachyon is still supporting Java 6 (though we may want to step away from Java 6 support soon).

**Comment by aaudiber** [comment]
@apc999 I've removed the try-with-resources. I didn't realize Tachyon was supporting Java 6 - is it a problem that these two places use Java 7 only classes?

1. ReflectiveOperationException (class added in Java 7) used at TachyonException:68
2. InetSocketAddress.getHostString() (getHostString method added in Java 7) used at NettyDataServer:115

**Comment by jsimsa** [comment]
@aaudiber thank you for the fix ... could you add a TODO for the two classes you mentioned to fix the Java 6 incompatibility?

**Comment by jsimsa** [comment]
LGTM +1

**Comment by aaudiber** [comment]
submitted https://github.com/amplab/tachyon/pull/1777 to add the Java 6 support TODOs

**Comment by calvinjia** [comment]
@aaudiber Thanks for the improvement. For these kind of changes, could you open a JIRA ticket in the future?

LGTM

**Pull request merged**
