### PR TITLE
[TACHYON-142] Add utilities to support viewing logs from web UI

### PR DESCRIPTION
**Pull request by carsonwang**
It shows Master/Worker logs on web UI by listing the logs directory. 
It supports a custom logs directory setting. 
tachyonlogs

### CODE REVIEW

**Comment by calvinjia** [comment]
@carsonwang Thanks for the new feature. How is the logs page currently being served (ie. logs.jsp)? Could you attach a screenshot of the new page?

**Comment by carsonwang** [comment]
@calvinjia  A screenshot is attached. It simply lists the log files in the directory. A user can click the log file to view it in the browser.

**Comment by calvinjia** [comment]
Oh I see, do you mind wrapping it in a page like our current ones? I think its important to preserve the style of UI so the user experience is good.

**Comment by carsonwang** [comment]
Ok, in that case I'll have to add a jsp file and a servlet. When a user click a log file to read it, do you also want to wrap it in a page?

**Comment by rvesse** [comment]
I would suggest having both options i.e. you can read a portion of the log file within a page (and move through it - similar to what Tachyon Browse File System currently allows) and also have an option to View Raw which would actually write the log file as plain text to the client

**Comment by calvinjia** [comment]
The browse file page should be a good model to use. The download option may be a replacement for view raw, since the logs are probably going to be very large and not suitable for bulk display (or small enough to page through).

**Comment by rvesse** [comment]
Yep Download option is probably better than View Raw

**Comment by carsonwang** [comment]
Thanks for the input. Close this for now.

**Pull request closed without merging**
