### PR TITLE
[SMALLFIX] Use Netty Remote Reader by default

### PR DESCRIPTION
**Pull request by calvinjia**
Since Netty is the more supported client (supports read/write), this updates the default reader class to Netty as well.

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, please test this again

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by haoyuan** [comment]
We can’t automatically merge this pull request.

**Comment by apc999** [comment]
+1 LGTM

**Comment by haoyuan** [comment]
We can’t automatically merge this pull request.

**Comment by uronce-cc** [comment]
+1 LGTM

**Comment by gpang** [comment]
LGTM

**Comment by calvinjia** [comment]
@haoyuan conflicts resolved, thanks.

**Pull request merged**
