### PR TITLE
[SMALLFIX] Fix build of EvictorFactory

### PR DESCRIPTION
**Pull request by apc999**
EvictorFactoryTest  breaks build of Jenkins
This PR fixes it (with a little cleanup)

### CODE REVIEW

**Comment by apc999** [comment]
@calvinjia @gpang could you review this PR soon as build in master is breaking now

**Comment by gpang** [comment]
LGTM

**Comment by gpang** [comment]
Are you just leaving the fixup for the names for later?

**Comment by calvinjia** [comment]
+1 LGTM

**Pull request merged**
