### PR TITLE
[TACHYON-732]Metrics BlocksEvicted is not correct

### PR DESCRIPTION
**Pull request by carsonwang**
https://tachyon.atlassian.net/browse/TACHYON-732
Update metrics BlocksEvicted when a block is moved.

### CODE REVIEW

**Comment by uronce-cc** [comment]
+1 LGTM   the check failure is due to failing to fetch remote repo.

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
I guess this depends on the BlocksEvicted semantic, if it is demoted from a tier, does it count as evicted? It seems strange because it is still in Tachyon storage.

**Comment by uronce-cc** [comment]
May be better to have a separate `BlocksDemoted` semantic?

**Comment by carsonwang** [comment]
Thanks! Adding a `BlocksDemoted` seems to be clear as I do want to know how many blocks are moved to next tiers. Ok, I'll close this one and leave 0.7 as is. I'll open a new PR to master branch.

**Pull request closed without merging**
