### PR TITLE
[SMALLFIX]Add descriptions about achieving data locality on Spark with Tachyon

### PR DESCRIPTION
**Pull request by RongGu**
Add descriptions about achieving data locality on Spark with Tachyon

### CODE REVIEW

**Comment by calvinjia** [comment]
@RongGu Thanks for the additional documentation, should we also include something about setting `SPARK_LOCAL_HOSTNAME` in spark-env?

**Comment by RongGu** [comment]
@calvinjia Thanks for your comment. Yes, I have verified that setting `SPARK_LOCAL_HOSTNAME` also works. Acutally, the priority of "-h" is higher than setting `SPARK_LOCAL_HOSTNAME` in Spark. However, I agree with you on adding setting `SPARK_LOCAL_HOSTNAME` in our doc. It is more convinent.

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
LGTM, thanks!

**Pull request merged**
