### PR TITLE
[TACHYON-1549] Write unit test for ClientRWLock

### PR DESCRIPTION
**Pull request by caadecarvalho**

### CODE REVIEW

**Comment by caadecarvalho** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
@caadecarvalho thanks for the patch! For each test case (`@Test`), could you add a brief javadoc to explain what this test is looking for? Otherwise it looks good to me. Thanks

**Comment by caadecarvalho** [comment]
Thanks,  @apc999 . I pushed a new commit addressing your requests. Regards.

**Comment by caadecarvalho** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
+1 LGTM, thanks @caadecarvalho !

**Comment by caadecarvalho** [comment]
And I need to thank @aaudiber for the tip on how to address this!

**Pull request merged**
