### PR TITLE
[TACHYON-1484] Enable S3 Under Storage Tests to write data to S3

### PR DESCRIPTION
**Pull request by calvinjia**
https://tachyon.atlassian.net/browse/TACHYON-1484

### CODE REVIEW

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by gpang** [comment]
Is there something more general we could do about this? In which situations does UNDERFS_ADDRESS not need to be set?

**Comment by calvinjia** [comment]
@gpang 
I think it should be set in all situations, but unfortunately it causes the file prefix to be duplicated for local file system. It probably applies to any under storage that's not the default local storage, but I thought it made more sense to make it a whitelist rather than blacklist for now.

**Comment by gpang** [comment]
ok, sounds good

**Comment by gpang** [comment]
LGTM

**Comment by apc999** [comment]
+1 LGTM

**Pull request merged**
