### PR TITLE
[TACHYON-1527] Change URLs extension from Contributing-to-Tachyon.md

### PR DESCRIPTION
**Pull request by caadecarvalho**

### CODE REVIEW

**Comment by yupeng9** [comment]
Jenkins, add to whitelist.

**Comment by yupeng9** [comment]
ok to test

**Comment by caadecarvalho** [comment]
retest this please

**Comment by yupeng9** [comment]
Jenkins, add to whitelist.

**Comment by yupeng9** [comment]
ok to test

**Comment by aaudiber** [comment]
ok to test

**Comment by aaudiber** [comment]
add to whitelist

**Comment by aaudiber** [comment]
@caadecarvalho, If you want to push a new branch without adding unnecessary commits, you can use `git commit --amend` to create a new SHA for your latest commit, and then `git push -f` to overwrite the latest commit. Alternately, you should be able to retrigger Jenkins by commenting "Jenkins, test this please" now that you are on the whitelist.

You can roll back your latest 4 commits by going to this branch and running
```
git checkout HEAD~4
git push -f origin HEAD:refs/heads/caadecarvalho
```

**Comment by caadecarvalho** [comment]
Thanks, @aaudiber!

**Comment by apc999** [comment]
@caadecarvalho , by changing the ".html" suffix to ".md"
the compiled the html file for this md file which is a part of Tachyon document (http://tachyon-project.org/documentation/Contributing-to-Tachyon.html) will not be able to give a correct hyper link as it is right now.

**Comment by apc999** [comment]
unless there is some way to make the replacement from .md file to .html during compilation using jekyll.

A bit more info here, md files under `docs/` in Tachyon code base will all be compiled to html files and become the website of http://tachyon-project.org/documentation

**Comment by caadecarvalho** [comment]
Thanks for the info! So it won't work. I'll try to figure out something else, because would be good if the hyperlinks from this file inside github worked.

**Comment by caadecarvalho** [comment]
Closing PR as it won't work.

**Pull request closed without merging**
