### PR TITLE
[TACHYON-987] Enable fault tolerant tests

### PR DESCRIPTION
**Pull request by gpang**
https://tachyon.atlassian.net/browse/TACHYON-987

### CODE REVIEW

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
@gpang it doesn't seem like this PR addresses 992?

**Comment by gpang** [comment]
oops, I renamed it.

I just wanted to run the tests on jenkins in hopes to see failures (I can't get failures locally...)

**Comment by calvinjia** [comment]
Oh I see, perhaps mark this as [WIP]?

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by uronce-cc** [comment]
Hmm, I cannot reproduce on my local machine too.

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by uronce-cc** [comment]
jenkins, test this please

**Comment by gpang** [comment]
jenkins, test this please

**Comment by uronce-cc** [comment]
jenkins, test this please

**Comment by uronce-cc** [comment]
jenkins, test this please

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by yupeng9** [comment]
@gpang , any update on this PR? Thanks.

**Comment by gpang** [comment]
I am working on fixing some of the local cluster code to enable these tests again.

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
@calvinjia @uronce-cc I think this is ready to be reviewed. I have tested it on Jenkins many times today, and have not hit a failure (before, it would happen once every few times). Thanks!

**Comment by yupeng9** [comment]
Thanks for investigating this flaky test case. What do you think the root cause is?

**Comment by uronce-cc** [comment]
jenkins, test this please

**Comment by uronce-cc** [comment]
+1 for @yupeng9 , I didn't understand the root cause through this PR too. It "just works?..."

**Comment by gpang** [comment]
Well, one reason was that certain properties were being carried over across different test classes. There was another PR a while ago that fixed that (https://github.com/amplab/tachyon/pull/1940), and I think that fixed a lot of the issues.

Unfortunately, I don't know if this fully works, since it only used to fail on jenkins (never locally).

**Comment by yupeng9** [comment]
I see. That's a reasonable hypothesis.

**Comment by yupeng9** [comment]
LGTM

**Comment by uronce-cc** [comment]
Probably...

**Comment by uronce-cc** [comment]
LGTM

**Comment by gpang** [comment]
I just want to clarify. I know the state that was carried over between tests was a source of flakiness in the test, so that is now fixed. I just don't know if there are other sources of flakiness...

**Pull request merged**
