### PR TITLE
[TACHYON-1293] use {@link ByteBuf}

### PR DESCRIPTION
**Pull request by siyangy**
https://tachyon.atlassian.net/browse/TACHYON-1293

### CODE REVIEW

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Thanks for this improvement! Could you also add a link to the Jira in the description?

**Comment by siyangy** [comment]
done

**Comment by gpang** [comment]
LGTM

**Comment by apc999** [comment]
+1 LGTM

**Comment by siyangy** [comment]
Jenkins, test this please

**Comment by aaudiber** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
LGTM

**Pull request merged**
