### PR TITLE
[TACHYON-1073] improve usage of assert with boolean value

### PR DESCRIPTION
**Pull request by maocorte**
Hi, this is my second NewContributor PR.

[link to Jira issue](https://tachyon.atlassian.net/browse/TACHYON-1073)

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by haoyuan** [comment]
@maocorte  Thanks for the patch and it looks good to me.

Before merging your PR, could you finish one more setup? Your github profile on your local repo is not correctly set up so [your commits of this PR](https://github.com/amplab/tachyon/pull/1690/commits)  are not correctly linked to your github profile. For us to properly credit your contributions, would you spend a minute to set up your Github account by following the [Github instructions here](https://help.github.com/articles/setting-your-email-in-git/)

Thanks!

**Comment by maocorte** [comment]
@haoyuan OK, done, thank you for the suggestion.
Bests.

**Comment by haoyuan** [comment]
LGTM. Thanks!

**Pull request merged**
