### PR TITLE
[TACHYON-533] Implement Max Free alocation policy for the new allocator interface

### PR DESCRIPTION
**Pull request by carsonwang**
https://tachyon.atlassian.net/browse/TACHYON-533

### CODE REVIEW

**Comment by carsonwang** [comment]
One question, should the allocator add the `TempBlockMeta` to MetaManager? Currently this is done by the caller, i.e in `TieredBlockStore.createBlockMetaNoLock`. In this case, `allocate` may succeed but `mMetaManager.addTempBlockMeta` may still fail.

**Comment by calvinjia** [comment]
The current contract for the allocator is just to provide the location for the new block. The tiered store is responsible for modifying the metadata.

**Comment by carsonwang** [comment]
Got it. Thanks for the explanation, @calvinjia

**Comment by apc999** [comment]
+1 LGTM

**Comment by calvinjia** [comment]
+1 LGTM

**Pull request merged**
