### PR TITLE
[TACHYON-1558] rename tachyon.hadoop.Utils to tachyon.hadoop.HadoopUtils

### PR DESCRIPTION
**Pull request by marsfun**
https://tachyon.atlassian.net/browse/TACHYON-1558

### CODE REVIEW

**Comment by marsfun** [comment]
rename tachyon.hadoop.Utils to tachyon.hadoop.HadoopUtils

**Comment by gpang** [comment]
ok to test

**Comment by apc999** [comment]
+1 LGTM

**Comment by aaudiber** [comment]
LGTM, thanks for the contribution!

**Pull request merged**
