### PR TITLE
[TACHYON-737] Updated deploy module to download correct release based on tachyon and hadoop version

### PR DESCRIPTION
**Pull request by manugoyal**
Tested hadoop 1, hadoop 2.4, hadoop 2.6, and s3 manually.

### CODE REVIEW

**Comment by uronce-cc** [comment]
+1 LGTM. Thanks for the improvement!

**Comment by uronce-cc** [comment]
@manugoyal I found [a related JIRA ticket](https://tachyon.atlassian.net/browse/TACHYON-737), please assign it to yourself when you start the work, a similar PR is opened [here](https://github.com/amplab/tachyon/pull/1499).

**Comment by manugoyal** [comment]
I assigned it to myself

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
