### PR TITLE
[TACHYON-749] Clean up logging messages in ConfUtils

### PR DESCRIPTION
**Pull request by zongweiz**
https://tachyon.atlassian.net/browse/TACHYON-749

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test it please.

**Comment by apc999** [comment]
Jenkins, okay to test.

**Comment by apc999** [comment]
+1 LGTM

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
+1 LGTM

**Pull request merged**
