### PR TITLE
[SMALLFIX] Minor fix.

### PR DESCRIPTION
**Pull request by jsimsa**
This PR fixes style violations and capitalization.

@yupeng9 Should we get rid of the "Called via ..." comments? I understand that the original motivation was to make the code more readable, but as the code evolves, such comments become out of date and possibly incorrect, which can in fact hurt the readability.

### CODE REVIEW

**Comment by jsimsa** [comment]
@yupeng9 the checkstyle rule seems to be in conflict with the javadoc guidelines we have ... in particular, if the `@return` statement consists of multiple sentences, then the last sentence should end with '.'

**Comment by yupeng9** [comment]
I think `@return` is preferred to have a single sentence. For example, the doc in this PR could be rewritten to `the set of inode ids which are pinned; called via RPC`.

And the current rule doesn't enforce it if the state is multiple-line. 

On a side note, I agree with you that `called via` is not necessary, and could be removed. Thanks.

**Comment by gpang** [comment]
Yeah, you can get rid of the "called ..." parts.

**Comment by jsimsa** [comment]
@yupeng9 @gpang thank you for your feedback, I removed the "called ..." parts ... PTAL

**Comment by gpang** [comment]
Some of the method level comments are redundant of the `@return` lines (mainly the get* methods). Can those be removed?

**Comment by jsimsa** [comment]
@gpang done

**Comment by gpang** [comment]
LGTM

**Comment by yupeng9** [comment]
LGTM.

**Pull request merged**
