### PR TITLE
[TACHYON-587] Make Private helper methods in TieredBlockStore.java in alphabetical order

### PR DESCRIPTION
**Pull request by shenguoquan**
Hi @apc999. I am guoquan. I follow the instruction about the new contributor.

### CODE REVIEW

**Comment by haoyuan** [comment]
Jenkins, add to whitelist

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
+1 LGTM

**Comment by gpang** [comment]
LGTM

**Pull request merged**
