### PR TITLE
[Tachyon-1265] use heartbeat.await to replace sleep.

### PR DESCRIPTION
**Pull request by chen-tian**
https://tachyon.atlassian.net/browse/TACHYON-1265

### CODE REVIEW

**Comment by apc999** [comment]
+1 LGTM

**Comment by gpang** [comment]
Could you follow the example in HeartbeatThreadTest?

Particularly, I think you first have to setTimerClass() for the thread you want to control.

Then, you have to call await() at the start of the test.

Then, whenever you want the heartbeat thread to run, you have to call both:
schedule();
wait();

**Comment by yupeng9** [comment]
@chen-tian , in particular you can follow the instructions at this merged PR lately https://github.com/amplab/tachyon/pull/2084/files

**Comment by uronce-cc** [comment]
@chen-tian Thanks for the PR, are there any updates on this?

**Comment by chen-tian** [comment]
Hi Chang,

I am working the space reserver issue lately, and have gave calvin an
update about my situation -- busy with visitors and an LA trip.

I will work on 1265 probably this weekend or next week. If it blocks you,
you guys can fix that first.

**Comment by yupeng9** [comment]
@chen-tian have you had a chance to update this?

**Comment by chen-tian** [comment]
Yupeng,

I left Calvin a message. You  guys can close my PR, and I will rebase it
when I get time. Too busy lately. Hopefully after the spring festival, I
will get someone in  China to work with me on making more contributions.

Sorry for the delay.

**Comment by yupeng9** [comment]
Thanks for the update!

**Pull request closed without merging**
