### PR TITLE
[SMALLFIX] Use Private Access pattern in IntegrationTestUtils

### PR DESCRIPTION
**Pull request by aaudiber**
Followup to https://github.com/amplab/tachyon/pull/2451

### CODE REVIEW

**Comment by aaudiber** [comment]
I'm coming for you next `FileSystemMasterIntegrationTest#getCapacityBytesTest`... >:|

Jenkins, test this please.

**Comment by yupeng9** [comment]
Does this approach suggest all the whitebox calls should be defined in `privateAccess` classes?

**Comment by aaudiber** [comment]
Yes, it makes it easier to refactor in case the name changes, and we can use the call hierarchy on the private access to see usages.

**Comment by aaudiber** [comment]
Jenkins, test this please.

**Comment by yupeng9** [comment]
LGTM

**Comment by apc999** [comment]
+1 LGTM

**Pull request merged**
