### PR TITLE
[TACHYON-1396] Added a man file for the TFS shell

### PR DESCRIPTION
**Pull request by HorizonNet**
https://tachyon.atlassian.net/browse/TACHYON-1396

### CODE REVIEW

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
very nice, thanks! actually we shall make this file auto generated in the future from java source code!

**Comment by apc999** [comment]
+1 LGTM

**Comment by uronce-cc** [comment]
+1 LGTM

**Comment by HorizonNet** [comment]
Jenkins, test this please

**Comment by yupeng9** [comment]
LGTM. Thanks for adding the man file!

**Comment by yupeng9** [comment]
As @apc999 said, it'll be easier for maintenance if this man file is generated from the source code, and actually it should be feasible since all the commands have been refactored out as one command per file. @HorizonNet , will you be interested in taking this?

**Comment by HorizonNet** [comment]
@yupeng9 Yeah, would definitely be interested in it. Have no idea how to do it yet, but will figure something out. Is there already a JIRA for this?

**Comment by yupeng9** [comment]
Here you go https://tachyon.atlassian.net/browse/TACHYON-1438 :)

You may have better ones, but one idea off the top of my head is to define the MAN description in each command, and have a shell command `manGen` like `thriftGen` or `protoGen` to generate the man file.

**Pull request merged**
