### PR TITLE
[TACHYON-1144] Determine write type through understorage/tachyon type.

### PR DESCRIPTION
**Pull request by calvinjia**
https://tachyon.atlassian.net/browse/TACHYON-1144

### CODE REVIEW

**Comment by apc999** [comment]
+1 LGTM

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
It seems to me you need to modify the default understorage and tachyon storage type. See https://github.com/amplab/tachyon/blob/master/minicluster/src/main/java/tachyon/master/LocalTachyonCluster.java#L141 where I modified the write type for LocalTachyonCluster.

**Comment by calvinjia** [comment]
@apc999 makes sense, thanks.

**Comment by apc999** [comment]
you might need to still keep `mMasterConf.set(Constants.USER_FILE_WRITE_TYPE_DEFAULT, "CACHE_THROUGH");`

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Pull request merged**
