### PR TITLE
[TACHYON-803] use SystemUtils.IS_OS_WINDOWS to check WINDOWS

### PR DESCRIPTION
**Pull request by chen-tian**
https://tachyon.atlassian.net/browse/TACHYON-803?filter=-1

### CODE REVIEW

**Comment by uronce-cc** [comment]
+1 LGTM

**Comment by calvinjia** [comment]
@chen-tian Could you change this in `NetworkAddressUtils.java` as well?

**Comment by apc999** [comment]
+1 LGTM. Actually, we may want a `OSUtils` in `common`, defining things like isWindows, isLinux, pathSeparator and etc.

**Comment by chen-tian** [comment]
@apc999 @calvinjia  Yep. I was thinking about the same thing when I did this change. But need to read the code more thoroughly to make sure I don't miss anything.  Anyway, I will work on it and let you guys know if I need help.

**Comment by calvinjia** [comment]
+1 LGTM

**Pull request merged**
