### PR TITLE
modify the fileInfo member to private

### PR DESCRIPTION
**Pull request by ConeyLiu**
I modified the member of FileInfo from public to private.

### CODE REVIEW

**Comment by haoyuan** [comment]
Jenkins, okay to test.

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Hi @ConeyLiu , is there a JIRA ticket for this change? Also, the files in the thrift/ directly should not be modified directly, since those files are generated by the thrift compiler.

**Comment by ConeyLiu** [comment]
@gpang I'am very sorry, I don't have read the developer document before, and my test is not correct totally. If i should open get a JIRA before?

**Comment by haoyuan** [comment]
@ConeyLiu , thanks for the interest. how about starting with a task here?

https://tachyon.atlassian.net/issues/?jql=project%20%3D%20TACHYON%20AND%20labels%20%3D%20NewContributor%20AND%20status%20%3D%20Open

**Comment by ConeyLiu** [comment]
@haoyuan thank you very much!

**Pull request closed without merging**
