### PR TITLE
[Tachyon-549] General Utilities of Block Worker

### PR DESCRIPTION
**Pull request by Yours-shupeng**
Make getMasterAddress() and getWorkerAddress() utilities functions which are used in many classes.

### CODE REVIEW

**Comment by apc999** [comment]
Thanks @Yours-shupeng, really appreciate your patch! Here is a bit complication, though:

Since last week, we rebased branch `worker_wip` to `rebased_worker_wip` and and all commits for worker improvement goes to the latter branch. The purpose of this rebase is to help merge this back to `master`. I suggest to hold this PR and merge it to the updated `master` branch in a few days. Is it good for you?

**Comment by apc999** [comment]
The code looks good in general. It will be better if you can also submit the unittest of `BlockWorkerUtils` as a part of this PR. Thanks!

**Comment by Yours-shupeng** [comment]
@apc999 Okay, thanks. So I will hold this PR until the master branch is updated.

**Comment by Yours-shupeng** [comment]
@apc999 Since `worker_wip` branch has many conflicts with the current `master` branch, can I close this PR and reopen another one to merge it into `master` branch?

**Comment by haoyuan** [comment]
Please do. The worker_wip has been merged into the master branch.

**Comment by apc999** [comment]
Yes, close this PR, open the new PR to merge to `master`, and reference this PR so people can track the discussion here. 

Moreover, the title should be prefixed by "TACHYON-549" rather than "Tachyon-549", so JIRA system can pick it up :)

**Pull request closed without merging**
