### PR TITLE
[TACHYON-1573] replace Constructor with Creates a new instance of {@l…

### PR DESCRIPTION
**Pull request by Brook-zh**
…ink CommandLineJob}

### CODE REVIEW

**Comment by haoyuan** [comment]
Jenkins, ok to test.

**Comment by apc999** [comment]
@Brook-zh thanks for submitting the patch to this new contributor task.
In your change, could you remove the trailing character `"`? Otherwise it looks good to me

**Comment by Brook-zh** [comment]
OK

发自我的 iPhone

**Comment by apc999** [comment]
+1 LGTM.

Thanks for the patch!

**Pull request merged**
