### PR TITLE
[TACHYON-1149] Create the parent folder in underFS for a file if it does not exist

### PR DESCRIPTION
**Pull request by yupeng9**
https://tachyon.atlassian.net/browse/TACHYON-1149

This is a hot fix. Will have a unit test in a follow-up PR.

### CODE REVIEW

**Comment by calvinjia** [comment]
@yupeng9 Thanks for the fix. I thought we were trying to move the ufs creates to the master side instead of client side. Shouldn't the parent dirs be created in the `create` call?

**Comment by yupeng9** [comment]
Then I guess such check was not ported over? I can look into it, but I think @jsimsa should have more insights.

**Comment by jsimsa** [comment]
The parent directories should have indeed been created in the create call. Can you describe the failing scenario?

**Comment by calvinjia** [comment]
@yupeng9 @jsimsa I think the bug is in the examples because the create call is not properly setting the `underStorageType` based on the parameters (only the output stream is). A quick fix would be to add the option to the create call in the examples.

**Pull request closed without merging**
