### PR TITLE
[SMALLFIX] pin command, typo fix

### PR DESCRIPTION
**Pull request by CruncherBigData**

### CODE REVIEW

**Comment by aaudiber** [comment]
Thanks for the fix! Do you mind amending the commit message to say `[SMALLFIX] Fix typo in pin command test`? The tickets listed are already addressed.

**Comment by CruncherBigData** [comment]
sure, done.

**Comment by aaudiber** [comment]
@CruncherBigData The title changed, but there are still a few issues:

1. The title still includes `[TACHYON-1376]`
2. SMALFIX should be SMALLFIX
3. There shouldn't be a space before the comma in the commit message and title
4. The commit message needs to be updated to match the new title. You can do this with `git commit --amend`

**Comment by CruncherBigData** [comment]
Done. Please let me know if there is anything else I need to do.

**Comment by aaudiber** [comment]
LGTM, thanks for the quick iteration :)

**Comment by CruncherBigData** [comment]
my pleasure. thanks for the comments.

**Pull request merged**
