### PR TITLE
[SMALLFIX] If data is already in Tachyon, no need to "load" again in tfs

### PR DESCRIPTION
**Pull request by uronce-cc**

### CODE REVIEW

**Comment by uronce-cc** [comment]
jenkins, test this please

**Comment by uronce-cc** [comment]
jenkins, test this please

**Comment by apc999** [comment]
/home/jenkins/workspace/Tachyon-Pull-Request-Builder/shell/src/main/java/tachyon/shell/TfsShell.java:190: Trailing whitespace found.

**Comment by uronce-cc** [comment]
jenkins, test this please

**Comment by jsimsa** [comment]
LGTM

**Pull request merged**
