### PR TITLE
[SMALLFIX] Fix compilation error by handling TachyonException

### PR DESCRIPTION
**Pull request by aaudiber**
Followup to https://github.com/amplab/tachyon/pull/2173

### CODE REVIEW

**Comment by calvinjia** [comment]
LGTM, was this a merge conflict resolution issue?

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by aaudiber** [comment]
Must have been since it got through the pull request builder

**Comment by aaudiber** [comment]
The referenced PR changed `promoteBlock` to be able to throw `TachyonException`, causing it to conflict with https://github.com/amplab/tachyon/pull/2225

**Comment by aaudiber** [comment]
Jenkins, test this please.

**Pull request merged**
