### PR TITLE
[TACHYON-1639]Add the Chinese version of documentation page of 'File System API'

### PR DESCRIPTION
**Pull request by summerDG**
Add the Chinese version of documentation page of 'File System API'. See https://tachyon.atlassian.net/browse/TACHYON-1639

### CODE REVIEW

**Comment by ifcharming** [comment]
ok to test

**Comment by RongGu** [comment]
Thanks @summerDG . Please add the screencast of the page layout:)

**Comment by summerDG** [comment]
Click http://www.tachyon-project.org/documentation/master/en/File-System-API.html and choose Chinese version.

**Comment by yupeng9** [comment]
LGTM. Thanks!

**Pull request merged**
