### PR TITLE
[SMALLFIX] Moved resourcePool to common package

### PR DESCRIPTION
**Pull request by yupeng9**

### CODE REVIEW

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
+1 LGTM

**Comment by calvinjia** [comment]
@yupeng9 Thanks for the patch, what kind of other things would go into the `resource` package?

**Comment by yupeng9** [comment]
I think anything related to resource management can go there in the future, such as configuration, scheduling, monitoring, logging, etc

**Comment by uronce-cc** [comment]
+1 LGTM

**Pull request merged**
