### PR TITLE
TACHYON-272: update wiki page for Maven installation

### PR DESCRIPTION
**Pull request by guozhangwang**

### CODE REVIEW

**Comment by rvesse** [comment]
Would it not make more sense just to point to the Maven projects download and installation instructions?

**Comment by dcapwell** [comment]
Tachyon has a history of putting remote docs in the project as well; I believe thrift install is also in the docs rather than a reference.

It's my preference to point to the docs from the other projects, but if that stance is taken, then thrift would also need to follow

**Comment by rvesse** [comment]
There doesn't seem to be a clear policy, some pages (e.g. Fault Tolerance) just point to remote docs while others like you point out replicate the installation instructions.

Consistently pointing to remote docs would be preferable because it is less prone to bit rot

**Comment by dcapwell** [comment]
I fully agree with you.

Hy can you comment? I believe your stance was to include rather than point

**Comment by haoyuan** [comment]
The reason to include is to make it easy for people to follow, especially for thrift (its official installation docs is not the best). 

The general idea is if the original official guide is very stable and good, we can just link to that. Otherwise, let's put the best doc in our website to make our developers easier.

**Pull request closed without merging**
