### PR TITLE
Update perf module as Tachyon-0.6.0 released

### PR DESCRIPTION
**Pull request by swatDong**
Update perf module with Tachyon-0.6.0 (actually the version is 0.7.0-SNAPSHOT)
A few change in `pom.xml`, and the remaining is in `perf/`

### CODE REVIEW

**Comment by haoyuan** [comment]
@swatDong  Thanks for doing this. I just merged the master branch into the perf branch. Do you mind updating the branch based on that?

**Comment by swatDong** [comment]
@haoyuan I've tested this on the latest master branch and this PR is based on it.
The only text changed in origin tachyon is the 3 lines in pom.xml, so it has no conflict.

**Comment by haoyuan** [comment]
We can’t automatically merge this pull request.
Use the command line to resolve conflicts before continuing.

**Comment by swatDong** [comment]
I'll check it.

**Pull request closed without merging**
