### PR TITLE
[TACHYON-555] Change member variables from no modifier to private in BlockStoreMeta

### PR DESCRIPTION
**Pull request by qnu**
https://tachyon.atlassian.net/browse/TACHYON-555

Changed member variables from no modifier to private final.

### CODE REVIEW

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
Jenkins, add to whitelist.

**Comment by apc999** [comment]
+1 LGTM

**Comment by haoyuan** [comment]
Thanks!

**Pull request merged**
