### PR TITLE
[TACHYON-1274] Fix lost worker test

### PR DESCRIPTION
**Pull request by aaudiber**
https://tachyon.atlassian.net/browse/TACHYON-1274

### CODE REVIEW

**Comment by calvinjia** [comment]
@aaudiber why does whitebox cause flakiness?

**Comment by aaudiber** [comment]
@calvinjia The issue with the use of whitebox was that we were replacing the `PrivateAccess` methods, e.g. 
```
public MasterBlockInfo getMasterBlockInfo(long blockId) {
  synchronized (mBlocks) {
    return mBlocks.get(blockId);
  }
}
```
with unsynchronized whitebox accesses. This wasn't the root cause of the test failure though, the root cause was that we weren't stopping BlockMaster between tests and weird things were happening with the heartbeat thread. The second commit actually fixes the flakiness.

**Comment by apc999** [comment]
@calvinjia , I think @aaudiber found that the whitebox is not the real cause of flakiness for this unit test case. But I feel in general this is still a good pattern to unit-test private members, and suggest to merge this PR.

**Comment by calvinjia** [comment]
LGTM

**Comment by apc999** [comment]
+1 LGTM

**Pull request merged**
