### PR TITLE
[Tachyon-446] add tachyon-common to poms

### PR DESCRIPTION
**Pull request by shimingfei**
add dependency of tachyon-common into core/examples/integration-tests/shell pom.xml

### CODE REVIEW

**Comment by calvinjia** [comment]
@shimingfei Thanks for the patch, could you please tag this with a JIRA ticket #?

**Comment by apc999** [comment]
LGTM
In general, I think it is good to declare dependencies explicitly in pom. @calvinjia

**Comment by calvinjia** [comment]
The actual changes LGTM

**Comment by shimingfei** [comment]
@calvinjia @apc999 
I have added JIRA ticket for this PR

**Comment by calvinjia** [comment]
Thanks!
+1 LGTM

**Pull request merged**
