### PR TITLE
[TACHYON-49] [PR 1/N] Refactor Tachyon Core into Separate Modules

### PR DESCRIPTION
**Pull request by abhirajbutala**
OVERVIEW
-----------------
This is the 1st (of N) pull request for refactoring work of the tachyon core code into separate modules. Currently, the pull request is for branch **split**. Eventually after all changes are made, we will merge it back into master.

The high level design of the proposed changes are captured in **tachyon49-design-02.pdf** on [TACHYON-49](https://tachyon.atlassian.net/browse/TACHYON-49) JIRA ticket.

To quickly summarize, we are targeting the following directory/sub-project structure:

```
tachyon/
	bin/
	conf/
	deploy/
	docs/
	libexec/
	pom.xml
	assembly/
		pom.xml
		src/
	common/
		pom.xml
		src/
	clients/
		pom.xml
		client/
			pom.xml
			src/
		examples/
			pom.xml
			src/
		hadoop/
			pom.xml
			src/
		shell/
			pom.xml
			src/
	servers/
		pom.xml
		src/
	underfs/
		pom.xml
		local/
			pom.xml
			src/
		hdfs/
			pom.xml
			src/
		glusterfs/
			pom.xml
			src/
	integration-tests/
		pom.xml
		common/
			pom.xml
			src/
		local/
			pom.xml
			src/
		hdfs/
			pom.xml
			src/
		glusterfs/
			pom.xml
			src/
```
More details about each sub-project can be found in the design document.

CHANGES IN THIS PR
--------------------------------
This pull request introduces the basic skeleton mentioned above, and moves files in their respective directories. Also, integration tests are separated out and these tests currently work for local underfs cluster. Details below:

* Updates to parent pom.xml to look for new directories.
* Separation of common components into **tachyon-common** module, along with corresponding unit tests. This includes components like thrift, and all classes that are common to both clients and servers.
* Separation of all clients in their respective projects under **clients/** directory, along with corresponding unit tests. This introduces **tachyon-client**, **tachyon-examples**, **tachyon-hadoop** and **tachyon-shell** sub projects.
* Separation of local underfs module from core and put it in **tachyon-underfs-local** module. Introduced a new unit test ```LocalUnderFileSystemTest.java```, which checks for the presence of local under file system. 
* Separation of all the integration tests (tests that need a cluster) from core into a separate project called **tachyon-integration-tests**. The **tachyon-integration-tests-common** contains all the tests, but it does not actually run the tests. Instead, we have a sub-project for every under file system, so a cluster with that underfs can be used to run the tests, by pulling them using maven surefire plugin. Currently, only the **tachyon-integration-tests-local** is introduced and all tests pass.
* Added ```log4j.properties``` files for tests in all the new modules introduced.
* Appropriate clean ups in various pom.xml files to reflect the changes in dependencies.
* For clean refactoring of the components, had to introduce a few changes in code. They are summarized below:
  * Replaced ```MasterInfo.COL``` constant with ```Constants.COLUMN_PREFIX``` constant, to unnecessary interdependencies between client and master are removed.
  * To remove the dependency of ```Constants.java``` on ```tachyon.client.RemoteBlockReader``` and ```tachyon.worker.DataServer``` classes, commented out the constants ```WORKER_DATA_SERVER_CLASS``` and ```USER_REMOTE_BLOCK_READER_CLASS``` and made appropriate changes wherever they were referenced.
  * Updated ```UnderFileSystemCluster.java``` to not treat ```LocalFileSystemCluster``` as the default cluster anymore, as the local underfs is now moved to a separate underfs project.
  * ```TestDFSIO.java``` is currently disabled. It is being removed as a part of Tachyon-362 anyway.
* Addressed merge conflicts when merging with upstream/split.

TESTING DONE
-----------------------
At this point the refactored code compiles properly and all unit tests (in respective modules) pass. Also, integration tests work with local underfs cluster. The reactor summary currently looks like this:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Tachyon Project Parent ............................ SUCCESS [19.036s]
[INFO] Tachyon Common .................................... SUCCESS [1:44.300s]
[INFO] Tachyon Clients ................................... SUCCESS [1.904s]
[INFO] Tachyon Clients - Client .......................... SUCCESS [16.038s]
[INFO] Tachyon Clients - Examples ........................ SUCCESS [12.678s]
[INFO] Tachyon Clients - Hadoop Client ................... SUCCESS [14.211s]
[INFO] Tachyon Clients - Shell ........................... SUCCESS [8.624s]
[INFO] Tachyon Under File System ......................... SUCCESS [1.059s]
[INFO] Tachyon Under File System - Local FS .............. SUCCESS [5.729s]
[INFO] Tachyon Under File System - HDFS .................. SUCCESS [6.515s]
[INFO] Tachyon Under File System - Gluster FS ............ SUCCESS [6.836s]
[INFO] Tachyon Project Core .............................. SUCCESS [35.702s]
[INFO] Tachyon Integration Tests ......................... SUCCESS [0.996s]
[INFO] Tachyon Integration Tests - Common ................ SUCCESS [5.596s]
[INFO] Tachyon Integration Tests - Local FS .............. SUCCESS [8:10.498s]
[INFO] Tachyon Project Assemblies ........................ SUCCESS [1.629s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:13.507s
[INFO] Finished at: Thu Apr 30 14:48:42 PDT 2015
[INFO] Final Memory: 47M/127M
[INFO] ------------------------------------------------------------------------
```

TODO / FUTURE PRs
-------------------------------
- Proper resolution to some commented out constants from Constants.java (mentioned above). Perhaps we should find them a new home.
- Make integration tests work for hdfs underfs cluster.
- Make integration tests work for glusterfs cluster.
- Make sure contract tests work.
- Rename core --> servers and appropriate changes.
- Updates to assembly.
- Revisit the usage of shade plugin.
- Updates to bin/, libexec/ and deploy/ directories and test all the changes.
- Updates to documentation and javadocs.
- Any other suggestions based on review comments.

### CODE REVIEW

**Comment by calvinjia** [comment]
@abhirajbutala Thanks for the patch! Just wondering, would it be a lot of effort to include the HDFS integration tests in this PR as well?

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by haoyuan** [comment]
Jenkins, add to whitelist.

**Comment by abhirajbutala** [comment]
@calvinjia Sure, working on getting them to work currently, shall update the PR (if it is still open) once its finished. As per offline discussions with @haoyuan and Bin, we decided to roll this out quickly, so multiple people can then jump in on the pending items.

**Pull request merged**
