### PR TITLE
[SMALLFIX] Remove unneeded import

### PR DESCRIPTION
**Pull request by aaudiber**

### CODE REVIEW

**Comment by calvinjia** [comment]
LGTM, tests don't have imports checked by the style checker?

**Comment by aaudiber** [comment]
They do, this is a semantic merge conflict

**Comment by aaudiber** [comment]
The conflict was with https://github.com/amplab/tachyon/pull/2045/files#diff-75db4be5a00ed6da9fccc434584001e0L13, which moved tachyon.client.BlockMasterClient to tachyon.client.block.BlockMasterClient. Another reason to aim for faster review cycles.

**Comment by miasantreble** [comment]
LGTM, please merge ASAP since this is breaking the build

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
