### PR TITLE
[TACHYON-724] Use tierLevel as primary key to index tiers in tiered storage

### PR DESCRIPTION
**Pull request by dongche**
JIRA: https://tachyon.atlassian.net/browse/TACHYON-724

Split the work in following steps, and this PR covers the 1st step.

1. Core change. 
It use `StorageLevelAlias` as the wanted StorageType, and set it as a property of `StorageTier`. Then use tier level instead of tier alias to indexing in `BlockMetadataManager`, `BlockStoreMeta`, and `BlockStoreLocation`. At last, update related code and test based on the new index.
Besides, decouple the relation of level and alias. In current code base, we can find logic like this `level = alias.value - 1`. This is not correct when user does not configure all the storage tier types. We should avoid calculating level from the alias value.
2. Rename `StorageLevelAlias` to `StorageTierType`. (it could be in 1st step, but the PR would be too large for review)
3. Finish TODO marked in the patch
4. clean the naming in variables, methods and comments. (tierAlias -> tierType)

After review and finalize the core change, the 2 - 4 steps minor changes will be followed.

### CODE REVIEW

**Comment by dongche** [comment]
@apc999 , could you please help to review this PR for tier level indexing? Thanks.

This PR impact lots of files... 
For reviewing easier, I guess you could firstly review classes `StorageTier`, `StorageLevelAlias`, `BlockMetadataManager`, `BlockStoreMeta` and `BlockStoreLocation`. Others are just corresponding changes based on them.

**Comment by apc999** [comment]
@dongche  Thanks for taking the JIRA and submitting the patch! 

The refactor will be very important to Tachyon codebase. Meanwhile the requirement of this JIRA will be updated to better work with the newly refactored master.
I am working on updating the JIRA description and creating sub-JIRAs under this. Will you be interested in taking and working on some?

The plan mainly includes multiple steps (i.e., multiple PRs):
- Replace 1-based storage type indicator (i.e., the tierAlias) with maybe an enum StorageType.
- Get rid of the use of StorageDirId which gets sent over RPC only to infer StorageType, but deliver maps from StorageType to blocks to master from worker directly 
- Update master to use StorageType.
- Update worker to work with StorageType but not tierAlias.

**Comment by apc999** [comment]
@dongche https://tachyon.atlassian.net/browse/TACHYON-724 is updated. 
I will probably take first one or two sub tasks, and feel free to assign other subtasks to you or someone else as 724 is in your lead :)  Also there might be missing steps in this JIRA, also feel free to create more. Again, this is an important improvement people were talking and wanting for a long time :)

**Comment by dongche** [comment]
@apc999 The plan looks good and thanks for updating the requirements. This is interesting. I am glad to work on some JIRAs in the plan after you add StorageType in https://tachyon.atlassian.net/browse/TACHYON-950. And yes, there might be other steps. I will add more during working on this improvement.

**Comment by apc999** [comment]
This PR is probably deprecated by https://github.com/amplab/tachyon/pull/1826

**Pull request closed without merging**
