### PR TITLE
[TACHYON-1641]Add the Chinese version of doc page 'Integrating Under Storage Systems'

### PR DESCRIPTION
**Pull request by summerDG**
Add the Chinese version of documentation page 'Integrating Under Storage Systems'. See https://tachyon.atlassian.net/browse/TACHYON-1641

### CODE REVIEW

**Comment by ifcharming** [comment]
ok to test

**Comment by RongGu** [comment]
Thanks @summerDG . Please add the screencast of the page layout:)

**Comment by summerDG** [comment]
Click http://www.tachyon-project.org/documentation/master/en/Integrating-Under-Storage-Systems.html and choose Chinese version.

**Comment by yupeng9** [comment]
LGTM. Thanks for the translation.

**Pull request merged**
