### PR TITLE
[SMALLFIX] make s3 underfs available for proxy-based access

### PR DESCRIPTION
**Pull request by rukyzhc**
Additional configurations for the S3UnderFileSystem which enable to use the proxy while access s3.

This modification makes it possible to adopt some other s3-compatible storage as the underfs.

btw, I append MD5 to put request while creating the dir.

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Thanks for the PR! Does this already have a jira ticket? Could you add the ticket to the title like the other PR titles, "[TACHYON-XXXX] PR title"?

Also, could you add a link back to the jira ticket in the PR description?

Thanks!

**Comment by rukyzhc** [comment]
Actually, this PR should relate to 2 issues.

1. new feature: support proxy access

2. bug fix: exception while creating dir without MD5 meta tag, tested by 'bin/tachyon runTests'. 
Here are the logs:
2015-10-19 13:41:24,945 ERROR  (S3UnderFileSystem.java:mkdirsInternal) - Failed to create directory: /data/default_tests_files
org.jets3t.service.S3ServiceException: Mismatch between MD5 hash of uploaded data () and ETag returned by S3 (d41d8cd98f00b204e9800998ecf8427e) for object key: data/default_tests_files_$folder$
	at org.jets3t.service.S3Service.putObject(S3Service.java:2123)
	at tachyon.underfs.s3.S3UnderFileSystem.mkdirsInternal(S3UnderFileSystem.java:504)
	at tachyon.underfs.s3.S3UnderFileSystem.mkdirs(S3UnderFileSystem.java:256)
	at tachyon.client.file.FileOutStream.<init>(FileOutStream.java:94)
	at tachyon.examples.BasicOperations.writeFile(BasicOperations.java:109)
	at tachyon.examples.BasicOperations.call(BasicOperations.java:80)
	at tachyon.examples.BasicOperations.call(BasicOperations.java:43)
	at tachyon.examples.Utils.runExample(Utils.java:103)
	at tachyon.examples.BasicOperations.main(BasicOperations.java:145)
2015-10-19 13:41:24,946 ERROR  (Utils.java:runExample) - Exception running test: tachyon.examples.BasicOperations@24b1d79b
java.io.IOException: Failed to create /data/default_tests_files
	at tachyon.client.file.FileOutStream.<init>(FileOutStream.java:95)
	at tachyon.examples.BasicOperations.writeFile(BasicOperations.java:109)
	at tachyon.examples.BasicOperations.call(BasicOperations.java:80)
	at tachyon.examples.BasicOperations.call(BasicOperations.java:43)
	at tachyon.examples.Utils.runExample(Utils.java:103)
	at tachyon.examples.BasicOperations.main(BasicOperations.java:145)
Failed the test!

**Comment by rukyzhc** [comment]
@gpang It's a bit late and I'll create issues tomorrow.

**Comment by apc999** [comment]
+1 LGTM

**Comment by apc999** [comment]
@rukyzhc , thanks for the patch! For me this patch provides an important fix and we really like it to be in branch-0.8 which will be cut today. So I just merged your PR instead of waiting for the title fix.

**Comment by calvinjia** [comment]
LGTM

**Comment by rukyzhc** [comment]
@apc999 My pleasure to contribute to the fascinating project.

Since you have already merged the PR, I will no longer create addition issues.

**Comment by rukyzhc** [comment]
@calvinjia  @apc999 I met a wired problem. After merge the code into master branch, I failed the 'bin/tachyon runTests' in my env. The working commit is 5d92b74cd309adaf64a92413d8860bc536f136e9(my branch) and the failed commit is 6ddd7e7f3288b011b7afa646d6cfbaa0ec11209c(master merged of this PR)

I'm now working on the problem

**Pull request merged**
