### PR TITLE
[SMALLFIX] Close TachyonFS in /blockInfo

### PR DESCRIPTION
**Pull request by danielfree**
TachyonFS should be closed after use, similar to other servlets.

### CODE REVIEW

**Comment by gpang** [comment]
Thanks for the fix! Do the close() calls have to be in a finally clause, or does it not matter?

**Comment by calvinjia** [comment]
@danielfree Would keeping around a TachyonFS object be a way around this, since we create a new one every get request?

**Comment by danielfree** [comment]
@gpang since close() does not affect actual response, how about wrap close() with another catch/exception?

**Comment by danielfree** [comment]
@calvinjia TachyonFS is a somehow 'heavy' class, it creates its own MasterClient and WorkerClient, my opinion is that it's better for us to refactor TachyonFS. If we create TachyonFS in BlockWorker, we still end up with two MasterClient objects.

**Comment by gpang** [comment]
@danielfree , I am confused with your response. I was saying that there are some code paths that could lead to not calling close() on the client. For example, if getUiFileInfo() throws an exception, it would catch the exception and return, before calling close().

My question is, does it matter if close() is sometimes not called? Would it just be easier to keep around a TachyonFS client for the servlet, like @calvinjia suggested?

**Comment by danielfree** [comment]
@gpang Ah I see...yes we should put close() in a final block. If we don't do close(), the webpage is still ok, though we will have one new client-heartbeat thread each time we refresh the page /blockInfo. 

For now I don't prefer to create TachyonFS in BlockWorker and pass it all the way down to servlets, because TachyonFS will spawn two more heartbeat threads so I suggest let's just close() as soon as possible.

**Comment by gpang** [comment]
Thanks @danielfree ! Does line 108 need a close() before the return?

**Comment by danielfree** [comment]
@gpang Good catch! I think it's better to have a close() wherever we can :)

**Comment by gpang** [comment]
I think this looks good, but I would like to understand more about it. Does not closing the client cause problems, and what would the problems look like?

**Comment by danielfree** [comment]
@gpang The problem with not closing the client is that the heartbeat thread is still there running. I discover this issue when monitoring TachyonWorker, each time I refresh /blockInfo webpage, I get one more thread showing up.  As an example here is a screenshot of thread monitor on my local running master branch Tachyon. 

screenshot

**Comment by gpang** [comment]
Ok, thanks for the info and thanks for the fix!

**Comment by gpang** [comment]
LGTM

**Comment by calvinjia** [comment]
@danielfree Since we are already creating a new `TachyonFS`, why not just put that line in the constructor and use the same one for the lifetime of the web server?

**Comment by danielfree** [comment]
@calvinjia There are both pros and cons. I'm a bit conservative about keeping a TachyonFS for web server because it will create more threads, which keeps more connection to master(MasterClient) and worker(WorkClient) even if we don't use the web. What do you think?

**Comment by calvinjia** [comment]
@danielfree Does the TachyonFS create more threads even if its the same one? If not, I think having 2 persistent threads is fine and saves the overhead of recreating the clients each time. But if new clients are created each request regardless, I think your way is better.

**Comment by danielfree** [comment]
@calvinjia The same TachyonFS won't create more threads each time, since we use TachyonFS in three servlets ( WebInterfaceBrowseServlet, WebInterfaceDownloadServlet and WebInterfaceWorkerBlockInfoServlet ),  how about creating each TachyonFS in servlets constructor and do close() in their destroy() method?

**Comment by calvinjia** [comment]
@danielfree 
I see your point, we can revisit this issue when we clean up how the web UI is handled (whether it should be the same process as the worker/master). For now I think your current fix is sufficient.

**Pull request merged**
