### PR TITLE
[TACHYON-1529] Add the project survey link to the UI.

### PR DESCRIPTION
**Pull request by calvinjia**
https://tachyon.atlassian.net/browse/TACHYON-1529

Example page: 
screen shot 2016-01-18 at 10 55 32 am

### CODE REVIEW

**Comment by aaudiber** [comment]
LGTM

**Comment by apc999** [comment]
LGTM

**Comment by aaudiber** [comment]
Jenkins, test this please.

**Comment by CruncherBigData** [comment]
I wrote this test case "setPinTest" it assumes that the size of the memory for tachyon is 10MB, did someone change anything that relates to such setting ?

**Comment by CruncherBigData** [comment]
ok I figured a way to write the use cases without using magic numbers. for now just comment line 89 and I will send a PR later.

**Comment by apc999** [comment]
@CruncherBigData , thanks

**Pull request merged**
