### PR TITLE
[WIP][TACHYON-1050][TACHYON-1052] Debug DataServerIntegrationTest

### PR DESCRIPTION
**Pull request by uronce-cc**
This PR is to see why the test fails, not to be merged.

### CODE REVIEW

**Comment by apc999** [comment]
I crated TACHYON-1050 to reenable `DataServerIntegrationTest`. Once you have solved this, feel free to submit patch to TACHYON-1050 (or also include TACHYON-1050 in title).

Thanks for making the effort!

**Comment by uronce-cc** [comment]
@apc999 Could you trigger jenkins? Thanks.

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by uronce-cc** [comment]
jenkins, test this please

**Pull request closed without merging**
