### PR TITLE
[TACHYON-894] Improve code return in TFsShellUtils

### PR DESCRIPTION
**Pull request by dongche**
JIRA: https://tachyon.atlassian.net/browse/TACHYON-894

Improve unnecessarily verbose `return` code

### CODE REVIEW

**Comment by haoyuan** [comment]
Jenkins, test this again.

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
+1 LGTM

**Pull request merged**
