### PR TITLE
[TACHYON-1285] Show error in shell loadMetadata when file doesnt exist

### PR DESCRIPTION
**Pull request by siyangy**
https://tachyon.atlassian.net/browse/TACHYON-1285

### CODE REVIEW

**Comment by aaudiber** [comment]
LGTM, thanks for making this improvement! This will greatly improve the experience for the next person to load the metadata for a nonexistent file through the shell :)

**Comment by calvinjia** [comment]
@siyangy Thanks for the fix, could you add a unit test for TFsShell verifying the new behavior?

**Comment by jsimsa** [comment]
LGTM

**Comment by yupeng9** [comment]
LGTM. Thanks for the fix!

**Pull request merged**
