### PR TITLE
[TACHYON-632] Removed unreferenced import

### PR DESCRIPTION
**Pull request by zhljen**
https://tachyon.atlassian.net/browse/TACHYON-632

### CODE REVIEW

**Comment by calvinjia** [comment]
Jenkins, ok to test.

**Comment by apc999** [comment]
@zhljen Thanks for the patch! A few format issue about this PR (and futures):
(1) Could you rename PR title to be 
"[TACHYON-632 ] Removed unreferenced import" 
(2) Could you put a url link to your JIRA ticket in description part? This is strongly recommended for all PRs so we can better track the JIRA activities.

**Comment by apc999** [comment]
the code looks good. I will LGTM this PR after title and description format get fixed. 

Thanks a lot!

**Comment by zhljen** [comment]
Thanks for your comments. I will fix them.

**Comment by apc999** [comment]
+1 LGTM.

Thanks for the patch!

**Pull request merged**
