### PR TITLE
[TACHYON-335] Automatically mount all block device mappings

### PR DESCRIPTION
**Pull request by uronce-cc**
The purpose and design considerations are explained in vagrant/provision/device.sh in the first commit.

### CODE REVIEW

**Comment by uronce-cc** [comment]
@calvinjia

**Comment by calvinjia** [comment]
Thanks for the patch! Will this work if the machine has only 1 disk that is much larger than the default 10gb vagrant mounts?

**Comment by uronce-cc** [comment]
Tests I've done:

1. 
Instance_Type: "m3.xlarge"
Block_Device_Mapping:
  - DeviceName: "/dev/sdb"
    VirtualName: "tachyon"
    Ebs.VolumeSize: "100"
    Ebs.DeleteOnTermination: "true"
  - DeviceName: "/dev/sdc"
    VirtualName: "ephemeral0"

2. 
Instance_Type: "t2.small"
Block_Device_Mapping:
  - DeviceName: "/dev/sdb"
    VirtualName: "root1"
    Ebs.VolumeSize: "100"
    Ebs.DeleteOnTermination: "true"
  - DeviceName: "/dev/sdc"
    VirtualName: "root2"
    Ebs.VolumeSize: "20"
    Ebs.DeleteOnTermination: "true"

**Comment by uronce-cc** [comment]
@calvinjia You mean the instance storage?

**Comment by uronce-cc** [comment]
@calvinjia Any device you specified in block device mapping will be mounted.

**Comment by calvinjia** [comment]
@uronce-cc could you provide the state of the box after its been provisioned (df is fine)? Thanks!

**Comment by uronce-cc** [comment]
take **Test2** for example:
```
[ec2-user@ip-172-31-35-2 ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda2       10G  2.4G  7.7G  24% /
devtmpfs        904M     0  904M   0% /dev
tmpfs           920M     0  920M   0% /dev/shm
tmpfs           920M   17M  904M   2% /run
tmpfs           920M     0  920M   0% /sys/fs/cgroup
/dev/xvdb        99G   61M   94G   1% /disk0
/dev/xvdc        20G   45M   19G   1% /disk1
```

**Comment by calvinjia** [comment]
Thanks for the clarification. The other question I have is why is this done for all providers and not just aws?

**Comment by uronce-cc** [comment]
oh, missed that point...

**Comment by uronce-cc** [comment]
weird, why it's still waiting to hear from jenkins?

**Comment by calvinjia** [comment]
@uronce-cc I think the test build system is down for maintenance.

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
Jenkins, retest this please.

**Comment by calvinjia** [comment]
+1 LGTM, the test seems stuck but this doesn't touch any Tachyon code so I think it should be good to go.

**Pull request merged**
