### PR TITLE
[TACHYON-590] Recover the reverted PR of TACHYON-590 (resolve conflicts to merge with the current codebase)

### PR DESCRIPTION
**Pull request by tianyin**

### CODE REVIEW

**Comment by apc999** [comment]
@tianyin , could you resolve the merge conflicts before I merge this PR? 
Thanks.

**Comment by tianyin** [comment]
@apc999 sure! finally it gonna to be merged :-) doing it!

**Comment by tianyin** [comment]
@apc999 I finished.

**Comment by apc999** [comment]
@tianyin sorry for the long delay and requiring you to resolving conflicts multiple times. Now it has been merged :)

**Comment by tianyin** [comment]
No a problem, @apc999 
Let me know if there's any problem with the PR.

**Pull request merged**
