### PR TITLE
[TACHYON-283]Inode based Access Control

### PR DESCRIPTION
**Pull request by shenguoquan**
Hi :
     The Inode based Access Control has been completed. This pull request adds authentication framework and implements the simple authentication. The Tachyon master service will do acl authorization check based on the authentication. In order to decouple the big new feature, the pull request has already been split to 9 sub-tasks. The function of each sub-task can be deduced from
the commit summary. Please feel free to give your comments. Thanks very much.

### CODE REVIEW

**Comment by apc999** [comment]
Thanks for the patch, @shenguoquan . 
Currently, it seems this PR tries to resolve multiple JIRA tickets? My personal opinion is we should keep one PR per JIRA, so we could keep each pr as small to ease review process. Any possibility to separate this PR into multiple ones?

**Comment by calvinjia** [comment]
+1 to incremental PRs

**Comment by shenguoquan** [comment]
@apc999 @calvinjia Thanks for your advice. I will send the pull request for each Jira. Because the TACHYON-482 and TACHYON-483 is cloesly tied with each other. I will put these two patches into a PR. We at firstly can talk about this PR.

**Comment by calvinjia** [comment]
@shenguoquan Thanks, could you close this PR if its no longer necessary?

**Comment by shenguoquan** [comment]
@calvinjia sure. Thanks for your comments.

**Pull request closed without merging**
