### PR TITLE
[TACHYON-1625] Add oss option in TACHYON_UNDERFS_ADDRESS in "bin/tachyon format"

### PR DESCRIPTION
**Pull request by ifcharming**
https://tachyon.atlassian.net/browse/TACHYON-1625

### CODE REVIEW

**Comment by aaudiber** [comment]
ok to test

**Comment by aaudiber** [comment]
tip: prefer linking to https://tachyon.atlassian.net/browse/TACHYON-1625

**Comment by aaudiber** [comment]
LGTM

**Comment by ifcharming** [comment]
Updated PR description. Thanks Andrew!

**Comment by aaudiber** [comment]
Jenkins, test this please.

**Comment by aaudiber** [comment]
add to whitelist

**Comment by calvinjia** [comment]
LGTM

**Comment by aaudiber** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
+1 LGTM

**Pull request merged**
