### PR TITLE
[TACHYON-711] Prevent block locking during eviction

### PR DESCRIPTION
**Pull request by calvinjia**
https://tachyon.atlassian.net/browse/TACHYON-710

### CODE REVIEW

**Comment by shimingfei** [comment]
yes, it is a potential problem. 
But currently, it will not happen. eviction only happens when client wants to request space or move a block, and functions in TachyonFS are synchronized on one lock. so during the eviction, client will not able to request worker to lock a block again.

**Comment by calvinjia** [comment]
@shimingfei multiple clients can talk to the same worker right?

**Comment by shimingfei** [comment]
yes, multiple clients can talk to the same worker, such as running Mapreduce with Tachyon, there is one TachyonFS client  in each map/reduce process.

**Comment by apc999** [comment]
+1 LGTM

**Comment by calvinjia** [comment]
@shimingfei 
I agree there won't be an issue if the client that locked the block is only doing reads. However, I don't think its a good idea to rely on client behavior, for example, the client may promote a block, which would then be deadlocked (since it would be waiting on the eviction lock). Another possibility would be locking a block and then doing other operations such as creating a block (which would dead lock on the eviction lock), before unlocking the block. Currently there is no way to guarantee the lock and unlock are called without any calls which would lead to the requiring the eviction lock.

**Comment by shimingfei** [comment]
@calvinjia 
yes, it is a potential issue, and the fix sounds reasonable.
+1 LGTM

**Pull request merged**
