### PR TITLE
[[TACHYON-1109]] Added the checkstyle rule disallowing trailing period at @param tag

### PR DESCRIPTION
**Pull request by yupeng9**
https://tachyon.atlassian.net/browse/TACHYON-1109

### CODE REVIEW

**Comment by apc999** [comment]
+1 LGTM

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by jsimsa** [comment]
What if the `@param` description is multiple sentences?

**Comment by yupeng9** [comment]
It's encouraged to use one sentence for the description. If there're multiple sentence elements, semicolons can be used for separation.

**Comment by jsimsa** [comment]
should we also require that the leading letter of the comment is lowercase? (our style convention is to use lowercase if the sentence does not end with a period)

**Comment by jsimsa** [comment]
Please fix up the param descriptions so that they match our convention (if there is no period at the end, the sentence should start with lowercase). Also, please resolve merge conflicts.

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by yupeng9** [comment]
@jsimsa , PTAL

**Comment by jsimsa** [comment]
LGTM

**Pull request merged**
