### PR TITLE
[TACHYON-763] Eliminate tachyon.ServerConstants

### PR DESCRIPTION
**Pull request by zongweiz**
https://tachyon.atlassian.net/browse/TACHYON-763

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
+1 LGTM

**Comment by apc999** [comment]
Jenkins, Okay to test

**Comment by haoyuan** [comment]
Jenkins, Okay to test

**Comment by haoyuan** [comment]
Jenkins, add to whitelist.

**Comment by apc999** [comment]
+1 LGTM

**Pull request merged**
