### PR TITLE
[TACHYON-1247] Fixed deadlock issue in BlockStoreContext and FileSystemContext 

### PR DESCRIPTION
**Pull request by yupeng9**
https://tachyon.atlassian.net/browse/TACHYON-1247

### CODE REVIEW

**Comment by calvinjia** [comment]
@yupeng9 Continuing the discussion from the other thread, the only reason these methods were originally synchronized is because of `resetContext`. It is used in `AbstractTachyonFS`. We wanted to prevent undefined behavior if methods were called while the context was being reset. After removing synchronized from these two methods, what's the behavior if reset is called concurrently? 

As for testing, couldn't you just acquire max clients then try to acquire another one and then release the others? The test should fail after a timeout (implying deadlock occurred).

**Comment by yupeng9** [comment]
@calvinjia , `AbstractTachyonFS` is extended only by `TachyonFS` which is a singleton. That means `reset` will be called during `TachyonFS`'s construction, when no client can access the contexts, right?

The idea of unit testing is promising, I'll give it a shot

**Comment by calvinjia** [comment]
@yupeng9 Its possible to initialize the contexts through `TachyonFileSystem` and then reinit them by initializing `TachyonFS`.

**Comment by yupeng9** [comment]
I see. Is it reasonable to require users to either use the new FS API or the old one, but not both at the same time?

I think it's unsafe to allow the pool to be reset at any given time. Suppose a client has been acquired, and it can be released after the pool is reset. This leads to expected state even with locking on context.

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
LGTM, let's keep the ticket open for a more permanent solution.

**Pull request merged**
