### PR TITLE
[TACHYON-679] Put shared test utils in an independent module

### PR DESCRIPTION
**Pull request by uronce-cc**
https://tachyon.atlassian.net/browse/TACHYON-679

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
@apc999, please review this PR

**Comment by apc999** [comment]
@uronce-cc , thanks for the patch! We think the benefit of having an additional module with only two classes is kinda marginal. Instead of adding this module but still to clean up the dependency on test-jar of tachyon-servers, we may want to split the two test util files and refactor them into other parts:

(1) for `TestUtils.java`,  `getIncreasingByteArray` and other buffer stuff can go to BufferUtils? `uniqPath` can may go to `pathUtils` and `writeBufferToFile` can may go to `fileUtils`
(2) for `TachyonFSTestUtils.java`, they seem to me legitimate to be a part of `src` of tachyon-client 

In this way, we can probably still clean up the dependency :)

**Comment by uronce-cc** [comment]
@apc999 thx for suggestion. I came up with the solution, but I thought maybe these utils are only for tests, and not so appropriate to put in main code base. hmm, yup, they may be useful for other parts too. I'll close and open another PR.

**Pull request closed without merging**
