### PR TITLE
[SMALLFIX] Add generated serial version ID

### PR DESCRIPTION
**Pull request by vesense**

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by vesense** [comment]
Could we merge and close this PR?

**Comment by apc999** [comment]
@vesense , thanks for the patch! Here could you provide a little bit more description to the PR, e.g., why we need a `serialVersionUID` for this particular class? My understanding is serialVersionUID facilitates versioning of serialized data. I am not quite familiar with `java.security` package, so is it the expected use of `Provider` subclasses?

Thanks.

**Comment by apc999** [comment]
Oh I see interface `Provider` implements `Serializable` indirectly.
+1 LGTM

**Pull request merged**
