### PR TITLE
[WIP] Initial support for reserving multiple blocks during writing

### PR DESCRIPTION
**Pull request by rvesse**
WIP - Please review and comment only, **DO NOT MERGE**

This change has not yet been performance tested and is merely presented as a way to gather feedback on the proposed approach.

### Approach 

When the block size is smaller than the file size the write performance
can be significantly reduced because the client keeps having to go back
to the master to obtain new block IDs.  This commit adds a framework for
allowing users to configure reserving multiple blocks at a time.  When
configured the client will reserve N blocks in a single request to the
master and won't need to go back to the master until those N blocks are
used up.

If the client ends up needing less blocks than were allocated the extra
blocks are cancelled when the write is completed.

### CODE REVIEW

**Comment by calvinjia** [comment]
Could you open a JIRA ticket for this please?

**Comment by calvinjia** [comment]
If you have benchmarked the improvement this feature brings, could you please provide the results? Thanks!

**Comment by rvesse** [comment]
No haven't had chance to benchmark yet, just wanted to get feedback on whether the basic approach looked sane

**Comment by calvinjia** [comment]
Oh okay, the reason I ask is because if the primary motivation behind this feature is to increase performance, it would be good to do some kind of sanity check to see that it does give good results to avoid doing a lot of work for little gain.

**Comment by rvesse** [comment]
Yes obviously the next step is to benchmark this proposed change and see if and how this improves performance

**Pull request closed without merging**
