### PR TITLE
[TACHYON-1649]Add the Chinese version of documentation page 'Running-Spark-on-Tachyon'

### PR DESCRIPTION
**Pull request by TeddyBear1314**
https://tachyon.atlassian.net/browse/TACHYON-1649

### CODE REVIEW

**Comment by haoyuan** [comment]
Jenkins, add to whitelist.

**Comment by haoyuan** [comment]
Jenkins, ok to test.

**Comment by ifcharming** [comment]
LGTM, thanks for the translation!

**Comment by yupeng9** [comment]
LGTM. Thanks!

**Pull request merged**
