### PR TITLE
[TACHYON-1479]make names of unit test in FUSE consistent with Tachyon code convention

### PR DESCRIPTION
**Pull request by ukulililixl**
add 's' to the static type

### CODE REVIEW

**Comment by ukulililixl** [comment]
sorry I forgot to include this link
https://tachyon.atlassian.net/browse/TACHYON-1479?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
@ukulililixl Thanks for the patch, but the changes don't seem to reflect the ticket's description?

**Comment by apc999** [comment]
@ukulililixl thanks for taking the JIRA and submitting the patch! 
This patch is definitely a good improvement. In addition, In the JIRA, I was aiming to change names of test cases: e.g., `testMkdir` in this file should be `mkDirTest`. Could you also add commits to this PR to address this name convention issue?

**Comment by calvinjia** [comment]
@ukulililixl I think our convention for `static final` is simply `ALL_CAPS` since these are constants. `sVariable` is reserved for variables with only a `static` modifier.

**Comment by gpang** [comment]
ok to test

**Comment by yupeng9** [comment]
@ukulililixl could you revert the change on the variable names? Other than that, this PR looks good.

**Comment by ukulililixl** [comment]
I feel so sorry I forgot to see it and I just find the changes on the
variable names have been reverted back.


2016-01-15 7:31 GMT+08:00 Yupeng Fu <notifications@github.com>:

**Comment by yupeng9** [comment]
@ukulililixl I'm not sure what you mean. The variables such as `sTEST_MASTER_ADDRESS` should be `TEST_MASTER_ADDRESS`. Or did you forget to push your recent change?

**Comment by ukulililixl** [comment]
sorry I'm confused with git. And I made a new push.

**Comment by yupeng9** [comment]
@ukulililixl thanks for the improvement! LGTM.

**Pull request merged**
