### PR TITLE
[TACHYON-620] Fix moveBlock where space is not allocated/freed before hand

### PR DESCRIPTION
**Pull request by apc999**
https://tachyon.atlassian.net/browse/TACHYON-620

This is a bug fix to correct `moveBlock`. Previously, `moveBlock` doesn't really make sure the target location has enough space. This PR adds `freeSpaceInternal` into `moveBlock` to ensure space requirement.

### CODE REVIEW

**Comment by calvinjia** [comment]
+1 LGTM

I will open a ticket for optimizing data/metadata operations & locking.

**Comment by shimingfei** [comment]
if the new location is AnyDirInTier in some layer, and there are several dirs in the layer, then moveBlockInternal will be not right

**Comment by calvinjia** [comment]
+1 LGTM

**Comment by apc999** [comment]
@shimingfei , Thanks for pointing out the issue! A patch commit uploaded.

**Pull request merged**
