### PR TITLE
[TACHYON-344] Add a batch script in Tachyon-Perf

### PR DESCRIPTION
**Pull request by RongGu**
Add a batch testing utility in Tachyon-Perf.
Usage: `perf/bin/tachyon-perf-batch SimpleWrite Clean some/where/xmls/`

### CODE REVIEW

**Comment by RongGu** [comment]
@calvinjia

**Comment by calvinjia** [comment]
+1 LGTM

**Comment by rvesse** [comment]
I've been working on something similar myself, will see if I can fold in some of my logic into this script

**Comment by RongGu** [comment]
okay, Rob, let me know if you have some findings. @rvesse

**Comment by rvesse** [comment]
Looking in more detail looks like my script does something different to your script so I'll submit it separately

**Pull request merged**
