### PR TITLE
[TACHYON-898] Enable LoginUser in CUSTOM mode

### PR DESCRIPTION
**Pull request by dongche**
JIAR: [TACHYON-898](https://tachyon.atlassian.net/browse/TACHYON-898)

In current login framework, the login user can only be fetched in SIMPLE mode. Getting login user will throw UnsupportedOperationException in other mode. In this PR, we enable getting login user in CUSTOM mode.

This issue was found when doing integration test in #1297 . Configured with CUSTOM mode, client side will throw unsupported exception when getting login user for connecting to server. This PR resolve this.

@ooq , @apc999 , could you help to review this? Thanks.

### CODE REVIEW

**Comment by ooq** [comment]
I think there is name ambiguity between `CUSTOM` mode and custom name. The former is for customized authentication provider, while the later allows applications to pass a name. Any solution for this?

**Comment by dongche** [comment]
How about rename the `custom name` to `application provided name`? If this is ok, I can change the variable name, methods name, and comments in code following this principle, to make them expressive and also different with `CUSTOM` mode.

**Comment by ooq** [comment]
@dongche This is a pretty good idea! I will review the PR.

**Comment by ooq** [comment]
LGTM. The name change really helps make the code much easier to understand. Thanks also for adding all the `CUSTOM` mode tests to match `SIMPLE` mode tests.

**Comment by apc999** [comment]
+1 LGTM

**Pull request merged**
