### PR TITLE
[SMALLFIX] Fix flaky RawTableIntegrationTest

### PR DESCRIPTION
**Pull request by uronce-cc**

### CODE REVIEW

**Comment by gpang** [comment]
Thanks for this fix!

Why does setting the buffer size fix the flakiness of the test?

**Comment by apc999** [comment]
Also, does it mean we should have corresponding check in `FileOutStream`.

```
java.io.IOException: Fail to cache: Failed to request 1048576
	at tachyon.thrift.WorkerService$requestBlockLocation_result$requestBlockLocation_resultStandardScheme.read(WorkerService.java:8913)
	at tachyon.thrift.WorkerService$requestBlockLocation_result$requestBlockLocation_resultStandardScheme.read(WorkerService.java:8891)
	at tachyon.thrift.WorkerService$requestBlockLocation_result.read(WorkerService.java:8825)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at tachyon.thrift.WorkerService$Client.recv_requestBlockLocation(WorkerService.java:376)
	at tachyon.thrift.WorkerService$Client.requestBlockLocation(WorkerService.java:361)
	at tachyon.worker.WorkerClient.requestBlockLocation(WorkerClient.java:359)
	at tachyon.client.block.LocalBlockOutStream.<init>(LocalBlockOutStream.java:63)
	at tachyon.client.block.TachyonBlockStore.getOutStream(TachyonBlockStore.java:140)
	at tachyon.client.file.FileOutStream.getNextBlock(FileOutStream.java:256)
	at tachyon.client.file.FileOutStream.write(FileOutStream.java:225)
	at tachyon.client.file.FileOutStream.write(FileOutStream.java:210)
	at tachyon.client.table.RawTableIntegrationTest.rawtablePerfTest(RawTableIntegrationTest.java:173)
```

**Comment by uronce-cc** [comment]
If user file buffer size is not set, the default 2MB will be used, however, `LocalTachyonCluster` is only assigned `10000` bytes, then when writing, client will first try to request a block from worker with user file buffer size, so there will be `Fail to cache: Failed to request 1048576`, `1048576` is `2MB`.

**Comment by apc999** [comment]
@uronce-cc , thanks for the explanation. Do you have a reason why this problem only happens for this particular test? It seems we set `10000` bytes to `LocalTachyonCluster` almost always, and never set `USER_FILE_BUFFER_BYTES` particularly.

**Comment by uronce-cc** [comment]
@apc999 When there is data written to Tachyon space, `USER_FILE_BUFFER_BYTES` will be set if we set `10000` bytes to `LocalTachyonCluster`, for example, `DataServerIntegrationTest`.

**Comment by uronce-cc** [comment]
jenkins, test this please.

**Comment by uronce-cc** [comment]
jenkins, test this please

**Comment by uronce-cc** [comment]
jenkins, test this please

**Comment by gpang** [comment]
LGTM

**Pull request merged**
