### PR TITLE
[TACHYON-1076] Clean up IsolatedTachyonFileSystem Integration Test

### PR DESCRIPTION
**Pull request by saveveltri**
https://tachyon.atlassian.net/browse/TACHYON-1076

Hi everyone,
    this is my first NewContributor issue.
Feel free to comment in case of any mistakes.

Bests

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
For your future PRs, please also add a link back to the jira ticket. Thanks for this patch!

**Comment by robbenti** [comment]
Thanks, I'll do it for my future PRs

**Comment by apc999** [comment]
+1 LGTM

**Pull request merged**
