### PR TITLE
[SMALLFIX] Minor code improvement for Client project

### PR DESCRIPTION
**Pull request by yupeng9**

### CODE REVIEW

**Comment by apc999** [comment]
+1 LGTM

**Comment by calvinjia** [comment]
@yupeng9 Could you resolve the merge conflicts please? Also for documenting variables, try to use `/** description */` if possible. Looks good otherwise.

**Comment by yupeng9** [comment]
Thanks for reviewing. Addressed your comments.

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by jsimsa** [comment]
LGTM +1

**Pull request merged**
