### PR TITLE
change the position of the stream after reading

### PR DESCRIPTION
**Pull request by shimingfei**
replace seek(oldPos)  by changing the position of the stream only

### CODE REVIEW

**Comment by shimingfei** [comment]
@pfxuan @haoyuan can you take a look?

**Comment by haoyuan** [comment]
Thanks @shimingfei ; Do you mind adding unit test for this?

Also, it will be great to go to the HDFS docs, create tests for all the different cases, and verify that our implement doesn't break the protocol. Could you please create a JIRA and a patch for this?

**Comment by shimingfei** [comment]
sure, I will

**Comment by haoyuan** [comment]
Thanks!

**Comment by shimingfei** [comment]
@haoyuan I have added test for the change.
and created another JIRA to address the testing for HDFS interface.
https://tachyon.atlassian.net/browse/TACHYON-261

**Pull request merged**
