### PR TITLE
[TACHYON-1507] Fix last check time in space reserver and session cleaner

### PR DESCRIPTION
**Pull request by shimingfei**
1. currently space reserver doesn't update last check time.

2. last check time in session cleaner doesn't record the duration of clean operation

### CODE REVIEW

**Comment by calvinjia** [comment]
@shimingfei Thanks for the fix, could you add a unit test verifying the behavior?

**Comment by apc999** [comment]
@shimingfei thanks for the fix. this PR looks good to me.
How about creating another JIRA to submit a followup PR to add a unit test?

**Comment by shimingfei** [comment]
@calvinjia @apc999 
Sorry for late replay, I will add the unit test in this PR. Thanks!

**Comment by shimingfei** [comment]
@apc999  @calvinjia  the code is rebased.
I will add test cases in another PR, Thanks!

**Comment by calvinjia** [comment]
SGTM, thanks for fixing this bug.

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
