### PR TITLE
[TACHYON-1082] Remove unused Tachyon parameters definition from Tachyon.Constants

### PR DESCRIPTION
**Pull request by shuhuai007**
Just remove constants:
DEFAULT_MASTER_MAX_WORKER_THREADS
DEFAULT_WORKER_MAX_WORKER_THREADS

https://tachyon.atlassian.net/browse/TACHYON-1082

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
@shuhuai007 Thanks for the patch, could you clean up the git history? It seems like other changes got mixed in.

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
LGTM

**Comment by gpang** [comment]
Actually, it looks like there are other commits here. Could you clean up the state? Thanks!

**Comment by shuhuai007** [comment]
I have remove  other commits

**Comment by apc999** [comment]
+1 LGTM, thanks for the patch!

**Pull request merged**
