### PR TITLE
[TACHYON-1643]Add the Chinese version of documentation page 'Lineage API'

### PR DESCRIPTION
**Pull request by summerDG**
Add the Chinese version of documentation page 'Lineage API'. See https://tachyon.atlassian.net/browse/TACHYON-1643

### CODE REVIEW

**Comment by ifcharming** [comment]
ok to test

**Comment by ifcharming** [comment]
LGTM

Thanks for the translation!

**Comment by RongGu** [comment]
Thanks @summerDG . Please add the screencast of the page layout:)

**Comment by summerDG** [comment]
Click http://www.tachyon-project.org/documentation/master/en/Lineage-API.html and choose Chinese version.

**Comment by yupeng9** [comment]
LGTM. Thanks.

**Pull request merged**
