### PR TITLE
[SMALLFIX] Enforced BlockStoreContext.resetContext's only caller to be ClientContext

### PR DESCRIPTION
**Pull request by yupeng9**

### CODE REVIEW

**Comment by apc999** [comment]
Could you elaborate the benefit of this PR?

**Comment by yupeng9** [comment]
The goal is to enforce the assumption that only ClientContext can call this method, thats why change the method signature to take ClientContext as input. Also, since ClientContext doesn't have public constructor, then only itself can call it by passing in a privately constructed instance internally.

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
LGTM

**Comment by aslanbekirov** [comment]
This caused a compilation error. Stack is below:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project tachyon-minicluster: Compilation failure
[ERROR] /Users/aslan/Developement/mesosphereWS/tachyon/minicluster/src/main/java/tachyon/master/LocalTachyonClusterMultiMaster.java:[272,18] cannot find symbol
[ERROR] symbol:   method reinitializeWithConf(tachyon.conf.TachyonConf)
[ERROR] location: class tachyon.client.ClientContext
[ERROR] -> [Help 1]

**Pull request merged**
