### PR TITLE
[TACHYON-1107] Remove executors in master clients

### PR DESCRIPTION
**Pull request by danielfree**
JIRA: https://tachyon.atlassian.net/browse/TACHYON-1107

Executors in master clients are never used, there is no need to create executors and pass them around various master clients.

### CODE REVIEW

**Comment by apc999** [comment]
@gpang, do you have particular reasons to keep `executors` around in those constructors?

**Comment by apc999** [comment]
+1 LGTM

**Comment by apc999** [comment]
@danielfree , could you resolve the merge conflicts? Then I will merge this PR.

Thanks!

**Comment by danielfree** [comment]
@apc999 conflicts resolved, thanks !

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
