### PR TITLE
[SMALLFIX] Port MasterInfoIntegrationTest

### PR DESCRIPTION
**Pull request by uronce-cc**

### CODE REVIEW

**Comment by gpang** [comment]
Is the solution to all the public methods to make it package private and put the test in the same package? Thanks!

**Comment by uronce-cc** [comment]
Yeah, I'd like to split it up into `filesystem/FileSystemMasterIntegrationTest`, `block/BlockMasterIntegrationTest`, etc, and then make the public methods to package private.

**Comment by gpang** [comment]
Ok, that sounds great.

**Comment by gpang** [comment]
LGTM

**Pull request merged**
