### PR TITLE
[TACHYON-1344] Remove main function of tachyon.master.LocalTachyonCluster

### PR DESCRIPTION
**Pull request by raysmilesmile**
tachyon.master.LocalTachyonCluster has a main function which is not used anywhere. Remove this main function.

https://tachyon.atlassian.net/browse/TACHYON-1344

### CODE REVIEW

**Comment by aaudiber** [comment]
Jenkins, add to whitelist

**Comment by aaudiber** [comment]
Jenkins, test this please.

**Comment by gpang** [comment]
ok to test

**Comment by gpang** [comment]
Thanks for the improvement!

**Comment by gpang** [comment]
LGTM

**Comment by yupeng9** [comment]
LGTM. Thanks!

**Pull request merged**
