### PR TITLE
[TACHYON-1056] Show the file/directory owner in the webpage when the filesystem is browsed through the web service

### PR DESCRIPTION
**Pull request by shenguoquan**
https://tachyon.atlassian.net/browse/TACHYON-1056

Show the file/directory owner in the webpage when the filesystem is browsed through the web service.

### CODE REVIEW

**Comment by shenguoquan** [comment]
Jenkins, test this please

**Comment by shenguoquan** [comment]
Jenkins, test this please

**Comment by ooq** [comment]
@shenguoquan Thanks for the PR. It seems most of the code change is also in #1574 . The changes LGTM. Whoever is more familiar with the Tachyon Web UI should probably double check.

**Comment by apc999** [comment]
@shenguoquan , I have merged https://github.com/amplab/tachyon/pull/1574
could you resolve the conflicts here? thanks

**Comment by shenguoquan** [comment]
Hi @apc999 , Thanks for your help. Sure, I will resolve these conflicts as soon as possible

**Comment by shenguoquan** [comment]
Hi @apc999  ， I have resolved conflicts. Please help me to look at. Thanks

**Comment by shenguoquan** [comment]
Jenkins, test this please

**Comment by ooq** [comment]
jenkins, test this please.

**Comment by shenguoquan** [comment]
Hi @apc999, @ooq , please help me to look at. THX

**Comment by ooq** [comment]
This PR LGTM.

**Comment by apc999** [comment]
+1 LGTM

**Pull request merged**
