### PR TITLE
[TACHYON-1164] Make TachyonFileSystem configurable

### PR DESCRIPTION
**Pull request by aaudiber**
https://tachyon.atlassian.net/browse/TACHYON-1164

### CODE REVIEW

**Comment by aaudiber** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
@aaudiber Thanks for the patch, I'm not sure if we should pass a copy of TachyonConf into TachyonFileSystem and use it because currently we are assuming that all confs come from `ClientContext.getConf`. Ideally we only want one configuration active on the client at a time.

**Comment by apc999** [comment]
@aaudiber , could you briefly describe the benefits of this change? Thanks.

**Comment by aaudiber** [comment]
The description is in the JIRA ticket, but I've talked to Calvin and decided that we should not be passing around TachyonConfs; `ClientContext.getConf` is the source of configuration truth.

**Pull request closed without merging**
