### PR TITLE
[TACHYON-1248] Undeprecated ASYNC_THROUGH write type and added examples

### PR DESCRIPTION
**Pull request by yupeng9**
https://tachyon.atlassian.net/browse/TACHYON-1248

### CODE REVIEW

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by aaudiber** [comment]
Do we have any integration tests for ASYNC_THROUGH?

**Comment by yupeng9** [comment]
Yes, the test is in `FileOutStreamAsyncWriteIntegrationTest`

**Comment by aaudiber** [comment]
LGTM

**Pull request merged**
