### PR TITLE
[TACHYON-278] Update checkstyle to check for extra spaces in open and close parentheses

### PR DESCRIPTION
**Pull request by marsishandsome**
https://tachyon.atlassian.net/browse/TACHYON-278

### CODE REVIEW

**Comment by haoyuan** [comment]
Jenkins, okay to test.

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by marsishandsome** [comment]
@haoyuan Any suggestions to this patch?

**Comment by haoyuan** [comment]
Thanks!

**Pull request merged**
