### PR TITLE
[TACHYON-1658]Add the Chinese version of documentation page 'Thrift'

### PR DESCRIPTION
**Pull request by summerDG**
Add the Chinese version of documentation page 'Thrift'. See https://tachyon.atlassian.net/browse/TACHYON-1658

### CODE REVIEW

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
ok to test

**Comment by ifcharming** [comment]
LGTM

Thanks for the translation!

**Comment by RongGu** [comment]
Thanks @summerDG . Please add the screencast of the page layout:)

**Comment by summerDG** [comment]
First, open page 'Build Master Branch'. Then click link 'Thrift 0.9.2'. Or you can directly click http://www.tachyon-project.org/documentation/master/en/Thrift.html

**Comment by yupeng9** [comment]
LGTM. Thanks.

**Pull request merged**
