### PR TITLE
[TACHYON-671] Make tachyon.worker.block.BlockLockManager.LockRecord static

### PR DESCRIPTION
**Pull request by sundapeng**
A simple fix for https://tachyon.atlassian.net/browse/TACHYON-671

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins,  test this please

**Comment by calvinjia** [comment]
+1 LGTM

**Comment by apc999** [comment]
+1 LGTM

**Comment by sundapeng** [comment]
Thank @calvinjia @apc999 and @haoyuan for your review and commit.

**Pull request merged**
