### PR TITLE
[TACHYON-1187] Remove the unused variable mLocation in BasicCheckpoin…

### PR DESCRIPTION
**Pull request by shuhuai007**
Please review 
https://tachyon.atlassian.net/browse/TACHYON-1187

### CODE REVIEW

**Comment by calvinjia** [comment]
Jenkins, ok to test.

**Comment by yupeng9** [comment]
LGTM. @shuhuai007, thanks for removing the unused variable. While we appreciate much your recent contributions, we encourage people to take 2 new contributor tasks at most, so that other people can take them to get familiar with Tachyon codebase and contribution process. Do you want to move on to take  [beginner tasks](https://tachyon.atlassian.net/browse/TACHYON-1184?jql=project%20%3D%20TACHYON%20AND%20labels%20%3D%20Beginner%20AND%20status%20%3D%20Open) or [intermediate tasks](https://tachyon.atlassian.net/browse/TACHYON-1204?jql=project%20%3D%20TACHYON%20AND%20labels%20%3D%20Intermediate%20AND%20status%20%3D%20Open)?

**Comment by apc999** [comment]
@yupeng9  don't we need to change `bin/tachyon` correspondingly otherwise the `runTests` will break

**Comment by yupeng9** [comment]
It seems `runTests` no longer includes `BasicCheckpoint`. @uronce-cc, do you have any ideas?

**Comment by shuhuai007** [comment]
@uronce-cc 
Any updates for this?

**Comment by uronce-cc** [comment]
`BasicCheckpoint` is removed from `runTests`.

**Comment by shuhuai007** [comment]
So why was this removed from runTests? Should we add it again?

**Comment by apc999** [comment]
@shuhuai007 In the long run, we should probably add this test back . But I think for this PR, we could keep it as is---incremental change is preferred to the code base :)
+1 LGTM for this patch. Merging it right now.

**Pull request merged**
