### PR TITLE
[SMALLFIX] Add example usage for IndexedSet

### PR DESCRIPTION
**Pull request by uronce-cc**

### CODE REVIEW

**Comment by uronce-cc** [comment]
@gpang PTAL

**Comment by yupeng9** [comment]
+1 LGTM

**Comment by apc999** [comment]
Thanks for the document improvement!

You probably need to reopen this PR to merge to master branch though, after #1464 is merged.

**Comment by calvinjia** [comment]
@uronce-cc Could you reopen this one to the master branch?

**Comment by uronce-cc** [comment]
Reopened in https://github.com/amplab/tachyon/pull/1505

**Pull request closed without merging**
