### PR TITLE
[MERGE] Updates Authorization branch 

### PR DESCRIPTION
**Pull request by calvinjia**
Resolves conflicts with master in the authorization branch

### CODE REVIEW

**Comment by calvinjia** [comment]
@sundapeng @apc999 
Only the last four commits are not from the master branch.

**Comment by sundapeng** [comment]
Thank @calvinjia for helping merge with master,  the pr LGTM, only two minor comments.

**Comment by sundapeng** [comment]
@dongche Do you have any comments?

**Comment by dongche** [comment]
LGTM, thanks for this merge work!

**Pull request merged**
