### PR TITLE
[TACHYON-1025] Replace m tachyon conf

### PR DESCRIPTION
**Pull request by chrislusf**
https://tachyon.atlassian.net/browse/TACHYON-1025

### CODE REVIEW

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by haoyuan** [comment]
Jenkins, add to whitelist.

**Comment by miasantreble** [comment]
Hi @chrislusf , I think you might have missed some occurrence of mTachyonConf within the tachyon.worker package. Here is more comprehensive list of files that you probably need to change:
	modified:   servers/src/main/java/tachyon/worker/block/BlockDataManager.java
	modified:   servers/src/main/java/tachyon/worker/block/BlockMasterSync.java
	modified:   servers/src/main/java/tachyon/worker/block/BlockWorker.java
	modified:   servers/src/main/java/tachyon/worker/block/PinListSync.java
	modified:   servers/src/main/java/tachyon/worker/block/TieredBlockStore.java
	modified:   servers/src/main/java/tachyon/worker/block/evictor/LRFUEvictor.java
	modified:   servers/src/main/java/tachyon/worker/netty/DataServerHandler.java
	modified:   servers/src/main/java/tachyon/worker/netty/NettyDataServer.java
	modified:   servers/src/main/java/tachyon/worker/nio/NIODataServer.java
	modified:   servers/src/test/java/tachyon/worker/block/BlockDataManagerTest.java

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by jsimsa** [comment]
Please fix these issues: https://amplab.cs.berkeley.edu/jenkins/job/Tachyon-Pull-Request-Builder/5266/org.tachyonproject$tachyon-servers/console

**Comment by apc999** [comment]
https://github.com/amplab/tachyon/pull/1678/ is open to continue this PR by merging the conflicts.

**Pull request closed without merging**
