### PR TITLE
[TACHYON-677]: Clean unused imports in tachyon.Version.java

### PR DESCRIPTION
**Pull request by sundapeng**
A simple fix for https://tachyon.atlassian.net/browse/TACHYON-677

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test it please

**Comment by apc999** [comment]
@sundapeng, thanks for the patch. The patch is good.
A few format requirement in general for this and future PRs.
- Could you update the PR title to be "[TACHYON-677] Clean unused imports in tachyon.Version.java" in order to be consistent to our PR format?
- Also could you add the link to the JIRA ticket in the description part?

The reason we want to have a consistent format across all PRs is to ease tracking the open-source activities. Thanks in advance.

**Comment by sundapeng** [comment]
Thank you for your comments. Already updated it according your suggestion.

**Comment by apc999** [comment]
+1 LGTM

**Comment by sundapeng** [comment]
Thank @apc999 and @haoyuan for your review and commit.

**Pull request merged**
