### PR TITLE
[SMALLFIX] Removed unused properties and leave a TODO

### PR DESCRIPTION
**Pull request by apc999**
if we find it is necessary to add these properties back.
Currently, they were not used in the code base.

### CODE REVIEW

**Comment by gpang** [comment]
did these config parameters have corresponding entries in the docs/?

**Comment by apc999** [comment]
@gpang they are not documented. Therefore this PR has no touch on docs/

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by gpang** [comment]
LGTM

**Comment by jsimsa** [comment]
LGTM

**Pull request merged**
