### PR TITLE
[TACHYON-1159] Add private constructor to tachyon.Format

### PR DESCRIPTION
**Pull request by mark-henry**
To resolve [[TACHYON-1159]](https://tachyon.atlassian.net/browse/TACHYON-1159).

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by mark-henry** [comment]
Wow you guys' tooling is really nice

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
@mark-henry  you are welcome. The errors from tests seem from Jenkins testing framework, not your PR.

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
Jenkins is getting a bit crazy now for some reason.

**Comment by aaudiber** [comment]
LGTM.

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
Passed! LGTM +1

**Pull request merged**
