### PR TITLE
[TACHYON-1093] Code formatting cleanup

### PR DESCRIPTION
**Pull request by andreareale**
- See PR #1683 (comments by haoyuan)

### CODE REVIEW

**Comment by yupeng9** [comment]
Thanks for the format cleanup. Since you're on this, could you also remove the comment "  // (andrea) why doesn't this method return a file.TachyonFile instance instead?" in TachyonFileSystemCore?

**Comment by andreareale** [comment]
Sure, commende removed. However, out of curiosity, do you have an answer to the question in my comment? Cheers!

**Comment by yupeng9** [comment]
Yeah, actually I am with you on that: we should always return tachyonFile instead of fileId. If you dont mind, could you open a PR to change the return type of `create` and `loadMetadata`?

**Comment by jsimsa** [comment]
LGTM +1

**Comment by yupeng9** [comment]
LGTM

**Pull request merged**
