### PR TITLE
[TACHYON-581] Improve javadoc of tachyon.worker.block.BlockStoreEventListener

### PR DESCRIPTION
**Pull request by qnu**
https://tachyon.atlassian.net/browse/TACHYON-581

Fix [TACHYON-581] Improve javadoc of tachyon.worker.block.BlockStoreEventListener, also add a reference from tachyon.worker.block.BlockStoreEventListenerBase.

### CODE REVIEW

**Comment by gpang** [comment]
Thanks for the patch!

I think the param variables should match the actual variable names, so they should be "userId" or "blockId", instead of "userID" or "blockID".

**Comment by qnu** [comment]
Thanks for suggestions! Fixes submitted.

**Comment by uronce-cc** [comment]
:+1: LGTM

**Comment by apc999** [comment]
+1 LGTM, thanks for the patch!

**Comment by calvinjia** [comment]
+1 LGTM.

I think eventually we will want to improve the javadocs to avoid just having `@param userId the ID of the user`, but that's something that occurs throughout the codebase.

**Pull request merged**
