### PR TITLE
[SMALLFIX] Reorganize worker clients

### PR DESCRIPTION
**Pull request by aaudiber**
Moved from `-common` to `-client` and changed from package `tachyon.worker` to `tachyon.client.worker`to be more consistent with other packages in `-client`

### CODE REVIEW

**Comment by apc999** [comment]
+1 LGTM.

Thanks for keeping common minimum

**Comment by gpang** [comment]
Should the other PR go in first?

**Comment by gpang** [comment]
LGTM

**Comment by aaudiber** [comment]
yea, lets merge this after the other one

**Comment by yupeng9** [comment]
LGTM. Thanks for the reorganization.

**Pull request merged**
