### PR TITLE
[TACHYON-1628-cn]Add the Chinese version of documentation page 'Architecture'

### PR DESCRIPTION
**Pull request by summerDG**
Add the Chinese version of documentation page 'Architecture'. See https://tachyon.atlassian.net/browse/TACHYON-1628

### CODE REVIEW

**Comment by ifcharming** [comment]
LGTM

**Comment by ifcharming** [comment]
ok to test

**Comment by summerDG** [comment]
Click http://www.tachyon-project.org/documentation/master/en/Architecture.html and choose Chinese version.

**Comment by yupeng9** [comment]
LGTM

**Pull request merged**
