### PR TITLE
[TACHYON-424] Calculate MD5 in S3OutputStream

### PR DESCRIPTION
**Pull request by calvinjia**
https://tachyon.atlassian.net/browse/TACHYON-424

Instead of using the jets3t convenience method to calculate MD5, we calculate it in the stream. This will give a large performance boost for large files due to the MD5 calculation being the bottleneck in machines with less CPU resource.

On a 5 node cluster of r3.large machines, there is a write performance increase of ~60%.

### CODE REVIEW

**Comment by uronce-cc** [comment]
Great to find the root cause! So before this PR, when new S3Object(mFile), jets3t will read the file from disk and compute the md5,  in this PR, the md5 is calculated in the process of writing the disk.  

+1 LGTM

**Comment by uronce-cc** [comment]
@calvinjia If jets3t uses DigestInputStream(FileInputStream) to compute md5 while reading the local file, it would have the same performance as this solution ?

**Comment by calvinjia** [comment]
@uronce-cc I think the md5hash needs to be available before the file is uploaded so calculating it on the upload might not work.

**Comment by apc999** [comment]
Really awesome! 
Thanks for the patch.

+1 LGTM.

**Pull request merged**
