### PR TITLE
[TACHYON-1582] Restructure POM: move fuse into integration 

### PR DESCRIPTION
**Pull request by apc999**
https://tachyon.atlassian.net/browse/TACHYON-1582
This is the first PR to achieve what proposed in https://tachyon.atlassian.net/secure/attachment/14000/POMstructurechangeproposal.pdf

### CODE REVIEW

**Comment by calvinjia** [comment]
LGTM, minor comment, do we want to rename `integration` to `integrations` in order to avoid confusion with `integration-tests`?

**Comment by apc999** [comment]
@calvinjia , as in the design doc, dir `integration-tests` will be renamed into `tests`

**Comment by uronce-cc** [comment]
LGTM ++

**Comment by jsimsa** [comment]
LGTM

**Pull request merged**
