### PR TITLE
[TACHYON-492] Update docs with new javadoc instructions

### PR DESCRIPTION
**Pull request by miasantreble**
https://tachyon.atlassian.net/browse/TACHYON-492

As the fix for TACHYON-490 has been merged, the corresponding section in the documentation needs to be updated with the new mvn commands

### CODE REVIEW

**Comment by gpang** [comment]
Jenkins, test this please.

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
+1 LGTM

**Comment by shaneknapp** [comment]
ok to test

**Comment by calvinjia** [comment]
+1 LGTM, thanks for updating the docs!

**Pull request merged**
