### PR TITLE
[TACHYON-1640]Add the Chinese version of documentation page 'Getting Started'

### PR DESCRIPTION
**Pull request by summerDG**
Add the Chinese version of documentation page 'Getting Started'. See https://tachyon.atlassian.net/browse/TACHYON-1640

### CODE REVIEW

**Comment by ifcharming** [comment]
ok to test

**Comment by ifcharming** [comment]
LGTM, thank you for the translation!

**Comment by RongGu** [comment]
Thanks @summerDG . Please add the screencast of the page layout:)

**Comment by summerDG** [comment]
Click http://www.tachyon-project.org/documentation/master/en/Getting-Started.html and choose Chinese version.

**Comment by yupeng9** [comment]
LGTM. Thanks!

**Pull request merged**
