### PR TITLE
removing license plugin definition, hopefully fixing broken snapshot build

### PR DESCRIPTION
**Pull request by shaneknapp**
this commit:
https://github.com/amplab/tachyon/pull/650

broke the snapshot build:
https://amplab.cs.berkeley.edu/jenkins/job/Tachyon-Snapshot/54/

so, i'm deleting this section of the pom to make it work again.

### CODE REVIEW

**Comment by rvesse** [comment]
Well it didn't break the pull request builds nor the master builds so clearly this is a build environment issue and ripping out the plugin is not the way to go.

It looks like the SNAPSHOT build is creating a local maven repo under the workspace (which IMO is a dumb idea) e.g.

    [WARNING] Missing header in: /home/jenkins/workspace/Tachyon-Snapshot/local-m2-repo/joda-time/joda-time/1.6.2/joda-time-1.6.2.pom

So it would be better to simply add a new exclude instead that excludes that directory, I'll open another PR that does that

**Comment by rvesse** [comment]
PR #682 instead modifies that POM to exclude the relevant directory from the license plugin checks

**Comment by hsaputra** [comment]
Thanks @rvesse, @shaneknapp please close this PR in favor of #682

**Comment by shaneknapp** [comment]
i totally agree that commenting out the section wasn't the "right" thing to
do.

i also looked at the build config for the snapshot and
found -Dmaven.repo.local=local-m2-repo in the maven args.  it's been
deleted and i'm running the build now (which seems to be chugging along
much happier than before).

**Comment by hsaputra** [comment]
Yep, it was actually my fault since I was  the one ask you to comment out the section.
Originally I just want to unblock the CI so HY could quickly commit the change until better fix comes along.
Thanks to @rvesse for stepping up =)

**Pull request closed without merging**
