### PR TITLE
Should not overwrite the existing variables defined in $CLASSPATH

### PR DESCRIPTION
**Pull request by pfxuan**
We should keep the existing variables when adding Tachyon jar files into $CLASSPATH

### CODE REVIEW

**Comment by haoyuan** [comment]
@pfxuan The issue is not in 0.6.0 anymore, right?

**Comment by pfxuan** [comment]
@haoyuan  I'm still using old version on real cluster, but will carefully test this new feature and send feedback to everybody. Thanks!

**Comment by haoyuan** [comment]
Thanks.

**Comment by haoyuan** [comment]
I'm going to close this for now. Please reopen it if the issue is still existing.

**Pull request closed without merging**
