### PR TITLE
[TACHYON-741] Remove unused LOG variable

### PR DESCRIPTION
**Pull request by pradeepbhadani**
New pull request (for #1419) to master branch.

### CODE REVIEW

**Comment by haoyuan** [comment]
Thanks @pradeepbhadani !

This branch has conflicts that must be resolved. Could you please merge the master branch or redo it on the master branch?

**Comment by pradeepbhadani** [comment]
@haoyuan  "LOG" variable do not exist on master branch in StorageDirTest.java file

**Comment by haoyuan** [comment]
aha. sorry about that. someone may have addressed that earlier. 

how about this one https://tachyon.atlassian.net/browse/TACHYON-901?jql=project%20%3D%20TACHYON%20AND%20labels%20%3D%20NewContributor%20AND%20status%20%3D%20Open

**Comment by haoyuan** [comment]
@pradeepbhadani , please let me know if there is anything we could help.

**Pull request closed without merging**
