### PR TITLE
[TACHYON-482&483] adding a authentication framework, simple authentication implementation and user mapping service 

### PR DESCRIPTION
**Pull request by shenguoquan**
The group mapping service is used by the authentication framework. they are closely tied with each other. So this pull request includes two Jira tickets:TACHYON-482 and TACHYON-483. Authentication is the first step to implement the Acl authorization in Tachyon.

### CODE REVIEW

**Comment by haoyuan** [comment]
We can’t automatically merge this pull request.

**Comment by shenguoquan** [comment]
Hi @haoyuan , I have seen you merged the master to acl branch. The PR is based the acl branch not merged from master. I will send a updated PR that the acl was merged. I am sorry for that. 
Thanks

**Comment by haoyuan** [comment]
Thanks @shenguoquan

**Comment by shenguoquan** [comment]
Hi @haoyuan, I have updated the patches according to the latest acl branch. If you have any idea, please feel free to comment on the PR. @dongche @sundapeng please join in the conversation.
Thanks

**Comment by haoyuan** [comment]
Jenkins, add to whitelist.

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
hi, @shenguoquan  is this PR still valid given we have other smaller incremental PRs coming in. If we are not working on this PR, feel free to close this one.

**Pull request closed without merging**
