### PR TITLE
[TACHYON-593] Merge security branch back to Master branch

### PR DESCRIPTION
**Pull request by shenguoquan**
https://tachyon.atlassian.net/browse/TACHYON-593

With the @apc999 and @ooq ' help, the simple authentication feature has now completed. I, @sundapeng and @dongche have discussed with @apc999 and @ooq found that it is a good time to merge this branch back to master branch. Please feel free to comment if you have other opinions. Thanks.

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test it please.

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
Hi @shenguoquan @sundapeng @dongche @ooq , sorry for the confusion. I just found this PR is not merging from the official security branch but the private repo, and unfortunately, it should be me who has permission to apply for merging from official security branch to master branch . So I reopen the same PR(https://github.com/amplab/tachyon/pull/1533) for the same purpose but from official security branch, and I will close this one. Sorry for @shenguoquan, let's work on #1533 .

**Comment by shenguoquan** [comment]
Hi @apc999 。 Never mind. We can continue to work on the PR you created. Thanks for your help

**Pull request closed without merging**
