### PR TITLE
[SMALLFIX] Cleanup during reading codes

### PR DESCRIPTION
**Pull request by uronce-cc**

### CODE REVIEW

**Comment by gpang** [comment]
Besides the merge conflicts, this looks good.

**Comment by uronce-cc** [comment]
@gpang PLTA

**Comment by gpang** [comment]
The previous PR got merged and caused conflicts in this one.

**Comment by uronce-cc** [comment]
@gpang PTAL

**Comment by gpang** [comment]
LGTM

**Pull request merged**
