### PR TITLE
[TACHYON-965] Taggins TODOs in all tachyon packages.

### PR DESCRIPTION
**Pull request by jsimsa**
This PR addresses https://tachyon.atlassian.net/browse/TACHYON-965. In particular, it tags all untagged TODOs in Tachyon code base with their author (or assignee if applicable) and cleans up the style of all TODOs.

### CODE REVIEW

**Comment by calvinjia** [comment]
@jsimsa Could you resolve the merge conflicts please?

**Comment by jsimsa** [comment]
Done. PTAL

**Comment by jsimsa** [comment]
Jenkins, test this please.

**Comment by yupeng9** [comment]
LGTM

**Comment by uronce-cc** [comment]
LGTM

**Comment by uronce-cc** [comment]
@jsimsa merge conflict.

**Comment by jsimsa** [comment]
Merged conflicts. PTAL

**Comment by gpang** [comment]
LGTM

**Pull request merged**
