### PR TITLE
[TACHYON-981] Remove redundant keyword "final" in "private" method in ServiceSocketBindIntegrationTest.

### PR DESCRIPTION
**Pull request by LeoOnHack**
[TACHYON-981] Remove redundant keyword "final" in "private" method in ServiceSocketBindIntegrationTest.

https://tachyon.atlassian.net/browse/TACHYON-981

### CODE REVIEW

**Comment by haoyuan** [comment]
Jenkins, okay to test

**Comment by yupeng9** [comment]
LGTM

**Comment by calvinjia** [comment]
@LeoOnHack I don't think the thrift file should be modified as it will be regenerated each time.

**Comment by gpang** [comment]
ok to test

**Comment by calvinjia** [comment]
@LeoOnHack Could you remove the modification to the thrift file?

**Comment by apc999** [comment]
agree what @calvinjia says about removing `common/src/main/java/tachyon/thrift/CommandType.java` which is generated by thrift compiler. @LeoOnHack could you exclude that file from this PR? Otherwise the PR looks good to me.

**Comment by LeoOnHack** [comment]
Thanks for the comments. I just reverted the changes on the thrift file. (adding "private" back to the enum).  I think this PR looks in better shape. :)

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
Jenkins, test this please.

**Pull request closed without merging**
