### PR TITLE
[TACHYON-1387] Use Ttl instead of TTL for naming

### PR DESCRIPTION
**Pull request by carsonwang**
https://tachyon.atlassian.net/browse/TACHYON-1387

### CODE REVIEW

**Comment by jsimsa** [comment]
LGTM

**Comment by uronce-cc** [comment]
LGTM, but I still feel better with TTL since it's a defined concept in Tachyon.

**Comment by caadecarvalho** [comment]
TTL it's a solid defined concept in IT Infrastructure, not sure if changing
that could be a good fit.

​@caadecarvalho

**Comment by jsimsa** [comment]
my two cents are that `TTL` and `Ttl` have the same meaning it is the same concept and the only difference is capitalization

the problem with using `TTL` consistently is that it violates the recommended style guide and also 3rd party code generation tools such as `thrift` create `getFoo()` getters even if the field name is `FOO` (so we end up with thrift generated `getTtl` and hand written `getTTL` elsewhere).

@aaudiber

**Comment by aaudiber** [comment]
@jsimsa summed up my thoughts nicely. I would only add that in addition to Thrift unavoidably generating `getTtl`, our protocol buffer code is also generating `getTtl`.

One alternative is to stop using the abbreviation and spell it out with `getTimeToLive`. This is done by https://docs.oracle.com/javase/7/docs/api/java/net/DatagramSocketImpl.html, which deprecated `getTTL` in favor of `getTimeToLive`

**Comment by caadecarvalho** [comment]
Good to know, thanks for the info and docs!

2016-01-08 15:38 GMT-02:00 Andrew Audibert <notifications@github.com>:

**Comment by apc999** [comment]
@aaudiber `getTimeToLive` is a bit verbose and it may not be obvious to people TimeToLive here is TTL.

**Comment by apc999** [comment]
I am good with this PR.

**Comment by aaudiber** [comment]
+1 LGTM

**Pull request merged**
