### PR TITLE
[TACHYON-1356] removed implicit final from PathUtils methods

### PR DESCRIPTION
**Pull request by ujvl**
https://tachyon.atlassian.net/browse/TACHYON-1356

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, add to whitelist

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by ujvl** [comment]
Just wondering, is something out of the ordinary here / did I miss something? (This is my first PR to the project)

**Comment by aaudiber** [comment]
Thanks for the improvement @ujvl!

**Comment by aaudiber** [comment]
+1 LGTM

**Pull request merged**
