### PR TITLE
[TACHYON-1642]Add the Chinese verion of documentation page 'Java Setup'

### PR DESCRIPTION
**Pull request by summerDG**
Add the Chinese verion of documentation page 'Java Setup'. See https://tachyon.atlassian.net/browse/TACHYON-1642

### CODE REVIEW

**Comment by ifcharming** [comment]
ok to test

**Comment by ifcharming** [comment]
LGTM, thanks!

**Comment by RongGu** [comment]
Thanks @summerDG . Please add the screencast of the page layout:)

**Comment by summerDG** [comment]
Click http://www.tachyon-project.org/documentation/master/en/Java-Setup.html and choose Chinese version.

**Comment by yupeng9** [comment]
LGTM. @summerDG, the link above of Chinese will only be available after this PR merged.

**Pull request merged**
