### PR TITLE
[TACHYON-524] Shutdown worker gracefully

### PR DESCRIPTION
**Pull request by RongGu**
https://tachyon.atlassian.net/browse/TACHYON-524

### CODE REVIEW

**Comment by RongGu** [comment]
The DataServer, Thrift and BlockMasterSync related threads have already shutdown. This PR adds the shutdown logic of WebServer and BlockDataManager.

**Comment by apc999** [comment]
+1 LGTM

**Comment by calvinjia** [comment]
+1 LGTM

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Pull request merged**
