### PR TITLE
[TACHYON-559] Removed variable 'LOG'  in RPCMEssageEncoder.java

### PR DESCRIPTION
**Pull request by luoli523**
[TACHYON-559] Removed variable 'LOG'  in RPCMEssageEncoder.java
https://tachyon.atlassian.net/browse/TACHYON-559

### CODE REVIEW

**Comment by calvinjia** [comment]
Jenkins, add to whitelist.

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
Could you clean up the commits in this PR? It seems to have some unnecessary history?

**Comment by luoli523** [comment]
ok I will

**Pull request closed without merging**
