### PR TITLE
[SMALLFIX] Moved comments to Javadoc in 'UnderStorageSystemInterfaceIntegrationTest'

### PR DESCRIPTION
**Pull request by HorizonNet**
Moved the existing comments about a test to Javadocs.

### CODE REVIEW

**Comment by yupeng9** [comment]
Thanks for the improvement! Could you also add docs for the thrown exception?

**Comment by jsimsa** [comment]
LGTM

**Comment by HorizonNet** [comment]
@yupeng9 Thanks for hint. I updated the PR accordingly.

**Comment by yupeng9** [comment]
LGTM. Thanks!

**Pull request merged**
