### PR TITLE
[SMALLFIX] Fix volatile increment race condition

### PR DESCRIPTION
**Pull request by aaudiber**
If the `launchTachyonWorkerContainers` callback is called from two threads at the same time, both `mNumAllocatedWorkerContainers ++` reads could happen before either set, causing the value to only get incremented by 1.

### CODE REVIEW

**Comment by calvinjia** [comment]
LGTM

**Comment by calvinjia** [comment]
@aaudiber Is there an easy way to unit test this?

**Comment by aaudiber** [comment]
@calvinjia Unfortunately no, we'd have to change ApplicationMaster so that the test can orchestrate the specific order in which the loads and sets happen.

**Comment by apc999** [comment]
I think this is not a real race condition as in worst case, we sleep longer until incremented value propagated to the other threads. But I am fine with this change as it is more easy to reason the correctness.

On a related note, I think we might need to use semaphore or some thing fancier from Guava to coordinate the timing, in the long run. and in that way we don't need to manually sleep.

**Comment by apc999** [comment]
oh, I take back my comments. This is a REAL race condition if you have multiple threads running `launchTachyonWorkerContainers`

**Comment by apc999** [comment]
But still, using semaphore might be a better way to coordinate.
+1 LGTM

**Pull request merged**
