### PR TITLE
Terminate Master process,  when exception happens during initialization

### PR DESCRIPTION
**Pull request by shimingfei**
Terminate Master process,  when exception happens during initialization,
Or the JVM process will not exit;

### CODE REVIEW

**Comment by haoyuan** [comment]
@shimingfei How did you trigger this issue?

**Comment by shimingfei** [comment]
@haoyuan In fact, I have never triggered this issue.
It is fault processing, if exception happens after some daemon threads are started, Master process will not exit, just like the worker side.

**Comment by shimingfei** [comment]
I just found a case which trigger the issue.
if configuration of tachyon.master.journal.folder is pointing to some place that doesn't exist, and Master failed to initialize, Master process will not exit, even it is failed to initialize.

**Comment by shimingfei** [comment]
I found another case"
if web port configured in TachyonMaster is already used in system, and Master failed to initialize webUI becaused of the conflict, TachyonMaster process still exists after the exception is thrown.

**Pull request merged**
