### PR TITLE
Fixes to the configuration files

### PR DESCRIPTION
**Pull request by gilv**
tachyon-env.sh.swift was out dated.
minor fix to core-sites.xml.template

### CODE REVIEW

**Comment by apc999** [comment]
+1 LGTM. Thanks for the patch!
@haoyuan , I think we shall probably also cherrypick this commit to branch-0.7

**Comment by haoyuan** [comment]
@gilv could you please commit this to branch-0.7 instead? thanks!

**Comment by gilv** [comment]
A bit embarrassing :), but i got stuck with git and repositories... somehow i don't manage to commit this to branch 07. Any chance you can handle it as is, if not, i will continue to dig trying to understand what i am doing wrong with git.

**Comment by calvinjia** [comment]
@gilv Thanks for opening the new PR, I will close this one since changes in the 0.7 branch will be merged to master.

**Pull request closed without merging**
