### PR TITLE
[TACHYON-1361]adda javadoc for mTtlBuckets

### PR DESCRIPTION
**Pull request by TeddyBear1314**
https://tachyon.atlassian.net/browse/TACHYON-1361
I create a new PR for issue TACHYON-1361.make it more clear.
I made a lot of mistakes before,sorry! ! !

### CODE REVIEW

**Comment by aaudiber** [comment]
ok to test

**Comment by aaudiber** [comment]
Jenkins, test this please.

**Comment by gpang** [comment]
LGTM

**Comment by TeddyBear1314** [comment]
:+1: Thank you everyone, I'll do better!

**Pull request merged**
