### PR TITLE
Remove unused IOException in getFileBlocks in MasterInfo

### PR DESCRIPTION
**Pull request by shimingfei**
Remove unused IOException in getFileBlocks in MasterInfo

### CODE REVIEW

**Comment by hsaputra** [comment]
I think the getFileBlocks methods internally call getClientBlockInfo which still indicated can throw IOException.

**Comment by shimingfei** [comment]
In MasterInfo getClientBlockInfos doesn't throw IOException either.

**Comment by hsaputra** [comment]
Ah no worries, it was apparently call to getClientBlockInfos instead of getClientBlockInfo

**Comment by shimingfei** [comment]
it is not right that getClientBlockInfo throws IOException, so I also make the change.

**Comment by hsaputra** [comment]
+1 LGTM

Simplify Tachyon exception throwing

**Pull request merged**
