### PR TITLE
[TACHYON-1239] Improved logging message formats in tachyon-minicluster

### PR DESCRIPTION
**Pull request by HorizonNet**
https://tachyon.atlassian.net/browse/TACHYON-1239

### CODE REVIEW

**Comment by HorizonNet** [comment]
The failing test seems flaky and seems not to be related to the actual change.

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by haoyuan** [comment]
+1

**Comment by gpang** [comment]
LGTM

**Pull request merged**
