### PR TITLE
[TACHYON-528] Collect metrics for the new worker

### PR DESCRIPTION
**Pull request by carsonwang**
https://tachyon.atlassian.net/browse/TACHYON-528

### CODE REVIEW

**Comment by apc999** [comment]
Thanks @carsonwang  for this PR! 

After reviewing your PR, we feel the code here perfectly fits the application of using an `BlockMetaEventListener`, so your provided code can be triggered on certain events, and you can  increment counters on those events. As an example @calvinjia is builds `BlockHeartbeatReporter` in such a way. 

Currently to fully support the metrics collection need, I think there are two events missing in `BlockMetaEventListener` for your needs: abort block and evict block. I will add them and then we can come back to this PR to refactor it. Is it Okay for you on your side?  Suggestion? Concerns?

**Comment by carsonwang** [comment]
Sounds good to me, @apc999 ! For the number of BlocksPromoted, do we just use the move block event ? It is not sufficient to only check if the new location is the first tier, because moving a block from one dir to another in the same first tier is not a promotion. It would be helpful if the oldLocation is passed to the postMoveBlock event so we can determine if the block was promoted.

**Comment by carsonwang** [comment]
@apc999 , I noticed another issue in `postMoveBlock` event. The `newLocation` passed to it is not the actual new location as it could be anyTier or anyDirInTier. I think we need pass the actual new location so the event subscriber knows which dir and tier the block was moved to. For example `BlockHeartbeatReporter` listens this event and gets the storageDirId from the newLocation.

**Comment by apc999** [comment]
Hi @carsonwang , according to the discussion, I have pushed change to `BlockMetaEventListener`. please take a look. Thanks!

**Comment by carsonwang** [comment]
@apc999 , I refactored the code that uses the block events. Please help review it. Thanks!

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
Thanks for the patch. It becomes much cleaner than the last iteration.

+1 LGTM

**Comment by apc999** [comment]
Jenkins, test this please.

**Pull request merged**
