### PR TITLE
[TACHYON-795] Improve JournalSerializable interface to enable stream serialization.

### PR DESCRIPTION
**Pull request by uronce-cc**
http://tachyon.atlassian.net/browse/TACHYON-795

### CODE REVIEW

**Comment by apc999** [comment]
@uronce-cc , please update the PR description with a JIRA link ?

**Comment by gpang** [comment]
Could you resolve conflicts, and fit this functionality with the updated api? Thanks!

**Comment by uronce-cc** [comment]
Resolved.

**Comment by gpang** [comment]
LGTM

**Pull request merged**
