### PR TITLE
[TACHYON-1157] Provide default options builders

### PR DESCRIPTION
**Pull request by shuhuai007**
Please review
https://tachyon.atlassian.net/browse/TACHYON-1157

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
The patch looks good  in general. Thanks!

**Comment by apc999** [comment]
+1 LGTM

**Comment by aaudiber** [comment]
LGTM

**Comment by apc999** [comment]
Jenkins, test this please.

**Pull request merged**
