### PR TITLE
[TACHYON-1511] Fix tier lookup in RoundRobinAllocator

### PR DESCRIPTION
**Pull request by aaudiber**
https://tachyon.atlassian.net/browse/TACHYON-1511

Previously we stored a Map from tier to latest directory index
for that tier. However, the keys were references to StorageTierViews,
which are not globally unique. This resulted in lookups always
returning null. This change uses the String tier aliases as keys
instead.

### CODE REVIEW

**Comment by yupeng9** [comment]
LGTM

**Comment by calvinjia** [comment]
@aaudiber thanks for the fix, would it be possible to catch this in a unit test?

**Comment by gpang** [comment]
How did this work before? Does StorageTierViews not have hashcode()/equals()?

**Comment by aaudiber** [comment]
@gpang It didn't work before - `StorageTierView` doesn't implement those methods. I've added tests which failed before the fix.

**Comment by aaudiber** [comment]
btw this is should fix the latest batch of build failures

**Comment by calvinjia** [comment]
LGTM

**Pull request merged**
