### PR TITLE
[TACHYON-1696] Mark tachyon.LocalTachyonClusterResource thread unsafe

### PR DESCRIPTION
**Pull request by beeflamian**

### CODE REVIEW

**Comment by beeflamian** [comment]
Jenkins, test this please

**Comment by haoyuan** [comment]
Jenkins, ok to test.

**Comment by aaudiber** [comment]
@beeflamian Thanks for the pull request! It looks like you need to import the NotThreadSafe class:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/jenkins/workspace/Tachyon-Pull-Request-Builder/tests/src/test/java/tachyon/LocalTachyonClusterResource.java:[66,2] cannot find symbol
  symbol: class NotThreadSafe
```

**Comment by beeflamian** [comment]
Jenkins, test this please

**Comment by beeflamian** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
@beeflamian sorry, our building system Jenkins has some problem pulling the source code from github.

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
+1 LGTM, thanks for the patch!

**Comment by beeflamian** [comment]
Thank you! Cheers! :beer:  @apc999 @aaudiber

**Pull request merged**
