### PR TITLE
[TACHYON-1120] Increase default hadoop version to 2.4.1 in pom setting

### PR DESCRIPTION
**Pull request by apc999**
https://tachyon.atlassian.net/browse/TACHYON-1120

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
LGTM

**Comment by yupeng9** [comment]
After this change is merged, we should also update the tutorials for deploying Tachyon, such as Configuring with Swift. @jsimsa

**Comment by jsimsa** [comment]
LGTM

**Pull request merged**
