### PR TITLE
[TACHYON-1671] Client renaming in web/examples/integration/kv

### PR DESCRIPTION
**Pull request by calvinjia**
Continuing #2572

### CODE REVIEW

**Comment by jsimsa** [comment]
LGTM

**Comment by aaudiber** [comment]
LGTM

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
LGTM

**Comment by apc999** [comment]
/home/jenkins/workspace/Tachyon-Pull-Request-Builder/examples/src/main/java/tachyon/examples/Performance.java:309: Line is longer than 100 characters (found 101).
Audit done.

**Comment by apc999** [comment]
+1 LGTM

**Pull request merged**
