### PR TITLE
improve efficiency of methods in InodeFolder

### PR DESCRIPTION
**Pull request by uronce-cc**
Fix TACHYON-287:
https://tachyon.atlassian.net/browse/TACHYON-287

### CODE REVIEW

**Comment by haoyuan** [comment]
@uronce-cc  Thanks for doing this. Could you please provide some numbers to measure this improvement?

**Comment by uronce-cc** [comment]
**before the PR**
getChild(int fid) called sequentially 10000 times, cost 1620 ms
getChild(String name) called sequentially 10000 times, cost 1602 ms
**after the PR**
getChild(int fid) called sequentially 10000 times, cost 111 ms
getChild(String name) called sequentially 10000 times, cost 33 ms
getChild(int fid) called sequentially 10000 times, cost 110 ms
getChild(String name) called sequentially 10000 times, cost 37 ms
getChild(int fid) called sequentially 100000 times, cost 32 ms
getChild(String name) called sequentially 100000 times, cost 224 ms

**Comment by uronce-cc** [comment]
**Before PR**
Used Memory = 10477264B when number of files = 10000
getChild(int fid) called sequentially 10000 times, cost 1549 ms
getChild(String name) called sequentially 10000 times, cost 1615 ms

**After PR**
Used Memory = 39778432B when number of files = 100000
getChild(int fid) called sequentially 100000 times, cost 33 ms
getChild(String name) called sequentially 100000 times, cost 153 ms

Used Memory = 11150200B when number of files = 10000
getChild(int fid) called sequentially 10000 times, cost 41 ms
getChild(String name) called sequentially 10000 times, cost 50 ms

**Comment by calvinjia** [comment]
+1 LGTM

**Comment by hsaputra** [comment]
+1

LGTM

**Pull request merged**
