### PR TITLE
[TACHYON-1398] Camel case the fileinfo shell command

### PR DESCRIPTION
**Pull request by yuzhiweilai**
Camel case the fileinfo shell command.We should use fileInfo to be consistent in file "shell\src\main\java\tachyon\shell\command\FileInfoCommand.java" and "integration-tests\src\test\java\tachyon\shell\TfsShellTest.java".

### CODE REVIEW

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by yuzhiweilai** [comment]
Jenkins, test this please

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by yuzhiweilai** [comment]
Jenkins, test this please

**Comment by aaudiber** [comment]
ok to test

**Comment by aaudiber** [comment]
add to whitelist

**Comment by aaudiber** [comment]
Jenkins, test this please.

**Comment by aaudiber** [comment]
Thanks for the PR, the current changes look good. Do you mind also updating `docs/Command-Line-Interface.md` and `shell/src/main/resources/tfs.man` to use "fileInfo" instead of "fileinfo"? You can find all usages of "fileinfo" in the git repository by running `git grep fileinfo`. Also, please add a link to the jira ticket to the PR description at the top of this page

**Comment by yuzhiweilai** [comment]
Ok,I will do that.

**Comment by apc999** [comment]
+1 LGTM

**Comment by yuzhiweilai** [comment]
https://github.com/amplab/tachyon/pull/2482

**Pull request merged**
