### PR TITLE
[TACHYON-1105] Enabled JSP compilation under profile compileJsp

### PR DESCRIPTION
**Pull request by yupeng9**
https://tachyon.atlassian.net/browse/TACHYON-1105

Added plugin `jspc` to precompile JSP files. The compilation is only enabled under profile `compileJsp` and the compiled output cannot be used to launch the web server, because `jspc` outputs tomcat code that is not compatible with our Jetty dependency.

### CODE REVIEW

**Comment by calvinjia** [comment]
@yupeng9 thanks for the patch, what's the typical workflow for developers after adding this or is it only for the build system?

**Comment by yupeng9** [comment]
It's enabled for the build system. And developers can use it for sanity check locally.

**Comment by apc999** [comment]
is it required to put the new profile under servers/pom? Currently all profiles are defined in parent. If it is not required, we may want to keep consistency

**Comment by jsimsa** [comment]
@yupeng9 thanks for this PR ... +1 for @apc999's comment, other than that it looks good to me

**Comment by yupeng9** [comment]
Moved the profile definition to parent pom.xml. @apc999 @jsimsa

**Comment by jsimsa** [comment]
LGTM

**Comment by yupeng9** [comment]
Jenkins, test this please

**Pull request merged**
