### PR TITLE
[TACHYON-1002] Remove unused file tachyon.conf.Utils

### PR DESCRIPTION
**Pull request by gautam-kumar**
https://tachyon.atlassian.net/browse/TACHYON-1002

### CODE REVIEW

**Comment by gpang** [comment]
Jenkins, add to whitelist

**Comment by gpang** [comment]
ok to test

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
LGTM

**Comment by jsimsa** [comment]
LGTM

**Pull request merged**
