### PR TITLE
[SMALLFIX] Fix format of configuration page in docs for easier read 

### PR DESCRIPTION
**Pull request by apc999**
In Configuration page:
- Some columns are too thin to read due to previous columns too wide---making them wrappable by using `&#8203;` as line-break indicator.
- Add stripes into tables so they are easy to read.

### CODE REVIEW

**Comment by calvinjia** [comment]
Should this be done for the other tables as well?

**Comment by apc999** [comment]
@calvinjia  other tables also changed.
Also fixed a few errors in tieredstored md

**Comment by calvinjia** [comment]
@apc999 is there another way to do the wrapping aside from div hardcoding? That feels very hacky

**Comment by yupeng9** [comment]
Can you just use newline to break?

**Comment by apc999** [comment]
@calvinjia auto text wrapping will break in arbitrary position, which looks worse. @yupeng9 I think linebreak will really break, while  this div will be only a hint

**Comment by jsimsa** [comment]
For consistency, shouldn't <div> for all the entries? Otherwise, it is not clear to someone unfamiliar with the problem why some entries use <div> and other don't. Also, ideally, we wouldn't use <div> directly, but define it in CSS for the <tr> elements that we want to linewrap.

**Comment by apc999** [comment]
@calvinjia  @yupeng9  @jsimsa I totally agree that <div> is hacky right now and not really scalable in the future. Actually I was thinking <div> approach as my last choice but unfortunately I also tried several other ways and none of them look better or less hacky. I think in the long run, these tables should be generated by program so we could make it smart to hint linebreak. But for this 0.8 branch, I feel it is kinda unnecessary to spend too much time hacking CSS

**Comment by apc999** [comment]
Before this PR:
screen shot 2015-10-29 at 5 48 20 pm

After this PR:
screen shot 2015-10-29 at 5 49 50 pm

**Comment by yupeng9** [comment]
@apc999, I'm cool with it, because the snapshots below show the change makes table layout strictly better. Thanks for the improvement!

**Comment by yupeng9** [comment]
LGTM

**Comment by apc999** [comment]
thanks @yupeng9 , in the long run, we might just wrap each field of a property name with div tag to hint the right word-break, and hopefully this is generated automatically.

**Comment by yupeng9** [comment]
Actually a zero-width space might work. http://stackoverflow.com/questions/12574538/why-doesnt-break-word-work-on-a-long-string-with-commas

**Comment by apc999** [comment]
I thought zero-width space or wbr are not supported in all browsers, e.g.,
IE

**Comment by yupeng9** [comment]
I think that's fine. Only IE6 and earlier doesn't support it. And I believe we can safely drop the support of IE6 (https://dev.modern.ie/ie6countdown/), because it has other visualization issues.

**Comment by apc999** [comment]
@yupeng9 , sounds good. `&#8203;` is used for now. We should automatically add this in the future.

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by yupeng9** [comment]
LGTM

**Pull request merged**
