### PR TITLE
[WIP] [TACHYON-49,TACHYON-221] Better integration tests

### PR DESCRIPTION
**Pull request by rvesse**
This PR is a follow up to previous PRs that have refactored Tachyon out into multiple modules

When I originally did the Under FS refactor as TACHYON-221 I used a multi-module approach for testing that allowed Tachyon builds to test multiple under file systems in a single build without the need to activate profiles explicitly.  However when the larger refactorings of TACHYON-49 those changes were lost and we went back to a situation with only being able to run a single under file system for integration testing in a single build.

This PR rectifies this by splitting the integration tests into a multi-module setup again and using advanced features of the Surefire plugin to simply re-use the test cases against each under file system in a separate module potentially allowing a single build to test all supported under file systems.

The under file systems that require no additional configuration (local and hdfs) are enabled to run by default, the implementations that need additional configuration (glusterfs and S3) must be enabled via a profile (`s3Test` and `glusterfsTest`).  For those that need additional configuration the enforcer plugin is now used to fail the build if the profile is activated but the user has not provided the necessary configuration.

Finally the Hadoop Contract tests are split out into a separate module that just runs those tests.  Since those tests require Hadoop 2.6.0 or higher (HDFS Contract Testing was only introduced in 2.6.0) the relevant test classes are only compiled when the `contractTest` profile is activated and the enforcer plugin is used to enforce that `hadoop.version` is set to 2.6.0 or higher.

### WIP

This is WIP and there are a couple more things to add yet:

- Integration test module for Swift
- Updated documentation on running integration tests

### CODE REVIEW

**Comment by calvinjia** [comment]
Thanks for the patch! Is the primary use case to test all the under file systems at once?

**Comment by rvesse** [comment]
Yes the idea is to be able to have a single build that tests as many under file systems as a given environment can support in a single build.  It also creates better separation between the test cases and the implementations being tested so that if a particular implementation fails it is clear what failed.

Also where under file systems need additional configuration in order to be tested the aim is to be more explicit to the user about what they need to configure and fail builds gracefully if they try and run a profile without the appropriate configuration

**Comment by calvinjia** [comment]
I definitely think the pom changes are a big improvement. One thing that's kind of weird now is we have split up ufs modules and (proposed) split up integration modules. Though I don't think the previous profile way was any better.

As for testing everything possible, would this work better as an optional mode and only have the local module test by default? Some benefits of only testing one ufs at a time are faster tests for devs who are not modifying ufs specific code and the ability to parallelize testing ufs (ie. in our Jenkins builds).

**Comment by rvesse** [comment]
Rebased against master, comments not yet addressed nor remaining work completed

**Comment by rvesse** [comment]
@calvinjia 

Have now addressed your main comments:

- HDFS tests are moved back to a `hdfsTest` profile that must be explicitly enabled to run
- Local tests are enabled by default but now in a `localTest` profile so can be explicitly disabled e.g.

        mvn clean package -PhdfsTest,!localTest

  Would run the HDFS tests without the local tests (note the use of `!` prior to the profile name to disable it)

So you can now do combinations of both what you and I wanted to do, either you can run a single build that tests all the implementations you want or you can run parallel builds each testing only a single implementation

**Comment by rvesse** [comment]
Added a new integration test module for OpenStack Swift enabled via `swiftTest` profile

**Comment by calvinjia** [comment]
@rvesse Is documentation the only remaining todo for this PR?

**Comment by rvesse** [comment]
Yes I believe so

**Comment by calvinjia** [comment]
@rvesse Are you planning to work on this one soon? It would be good to get it in, thanks!

**Comment by aaudiber** [comment]
Closing due to inactivity, feel free to reopen.

**Pull request closed without merging**
