### PR TITLE
[TACHYON-1518] Fix UnderStorageSystemInterfaceIntegrationTest.testListRecursive for OSS

### PR DESCRIPTION
**Pull request by luoli523**
fix the same problem as S3 integration test in UnderStorageSystemInterfaceIntegrationTest.testListRecursive

The jira link is here: https://tachyon.atlassian.net/browse/TACHYON-1518

### CODE REVIEW

**Comment by aaudiber** [comment]
LGTM

**Comment by aaudiber** [comment]
@luoli523 Please link the 1518 jira ticket in the description

**Comment by luoli523** [comment]
@aaudiber  I added the jira 1518 link in the PR description. Do you mean like this?

**Comment by aaudiber** [comment]
@luoli523 Yep, we have some tooling that looks for the link and updates the jira ticket. It's also convenient for anyone wanting to look at the ticket.

**Pull request merged**
