### PR TITLE
[SMALLFIX] Add two documentation on deployment

### PR DESCRIPTION
**Pull request by uronce-cc**

### CODE REVIEW

**Comment by uronce-cc** [comment]
Test failure should not be related to current PR, it is due to change to property key "tachyon.async.enabled", it should be able to be fixed when branch 0.8-docs merges branch master.

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by uronce-cc** [comment]
jenkins, test this please

**Comment by haoyuan** [comment]
jenkins, test this please

**Comment by uronce-cc** [comment]
once branch 0.8-docs merges master, I'll merge 0.8-docs into this PR, then the tests will pass.

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by yupeng9** [comment]
LGTM

**Comment by calvinjia** [comment]
Thanks for the update, LGTM

**Pull request merged**
