### PR TITLE
[SMALLFIX] Use hdfs1 API in KeyValueOutputCommitter

### PR DESCRIPTION
**Pull request by aaudiber**
This is needed to fix the hdfs1 build

### CODE REVIEW

**Comment by calvinjia** [comment]
@aaudiber Thanks for the fix, could we add a comment as to why we are using the older API? Also, is there any downside to using the older API?

**Comment by aaudiber** [comment]
@calvinjia Comment added. I don't think there's any downside to using the older API - we're just missing out on some syntax sugar (the approach we use is still supported in the new API)

**Comment by uronce-cc** [comment]
This is duplicated in https://github.com/amplab/tachyon/pull/2547, but if this is a blocker for you, LGTM ++

**Comment by aaudiber** [comment]
Jenkins, test this please.

**Comment by aaudiber** [comment]
@uronce-cc Fixing the build is higher priority than merging new code, so build fixes shouldn't be tacked on to other code which might cause them to get blocked, as happened with https://github.com/amplab/tachyon/pull/2547

**Comment by aaudiber** [comment]
Jenkins, test this please.

**Comment by aaudiber** [comment]
Jenkins, test this please.

**Comment by apc999** [comment]
+1 LGTM

**Pull request merged**
