### PR TITLE
add unit test for Dummy under fs

### PR DESCRIPTION
**Pull request by ShaoshanLiu**

### CODE REVIEW

**Comment by calvinjia** [comment]
@ShaoshanLiu Can you try setting the Dummy fs as the ufs implementation in a new test profile? I'm not sure if all the tests will pass, but a majority of them should.

**Comment by ShaoshanLiu** [comment]
Sure, where do I set this?

**Comment by ShaoshanLiu** [comment]
in core/pom.xml??

like this?
    <profile>
      <id>hdfsTest</id>
      <activation>
        <property>
          <name>test.profile</name>
          <value>hdfs</value>
        </property>
      </activation>
      <properties>
        <ufs>tachyon.LocalMiniDFSCluster</ufs>
      </properties>
      <dependencies>
        <dependency>
          <groupId>org.apache.hadoop</groupId>
          <artifactId>hadoop-minicluster</artifactId>
          <version>${hadoop.version}</version>
          <exclusions>
            <exclusion>
              <groupId>asm</groupId>
              <artifactId>asm</artifactId>
            </exclusion>
            <exclusion>
              <groupId>org.jboss.netty</groupId>
              <artifactId>netty</artifactId>
            </exclusion>
          </exclusions>
        </dependency>
      </dependencies>
    </profile>

**Comment by calvinjia** [comment]
@ShaoshanLiu Yup, you will see a property for ufs, there you can specify an UnderFileSystem that uses the dummy fs.

**Comment by ShaoshanLiu** [comment]
seems that I need to add a test cluster to wrap around the dummy UFS as well..let me work on it.  Thanks

**Comment by ShaoshanLiu** [comment]
When running the new test profile, we will get the following error on several tests.

readTooLarge[1](tachyon.worker.DataServerTest)  Time elapsed: 0.005 sec  <<< ERROR!
java.lang.IllegalStateException: Tachyon was not formatted! The journal folder is /var/folders/w5/sz0cv60x74nbv7x7bp__vh8c0000gp/T/Tachyon9005316898452586551U1427913706958/dfs/journal
	at com.google.common.base.Preconditions.checkState(Preconditions.java:149)
	at tachyon.master.TachyonMaster.<init>(TachyonMaster.java:137)
	at tachyon.master.LocalTachyonMaster.<init>(LocalTachyonMaster.java:106)
	at tachyon.master.LocalTachyonMaster.create(LocalTachyonMaster.java:159)
	at tachyon.master.LocalTachyonCluster.start(LocalTachyonCluster.java:190)
	at tachyon.worker.DataServerTest.before(DataServerTest.java:110)


Digging into more details, the root cause is that the dummyUFS would return an empty list of files when .list() is called,  then since it is an empty list, Master would think that it is not formatted correctly, I think this is by design, please let me know how you want to proceed.

Thanks and I have updated the PR with the changes. 

Shaoshan

**Comment by ShaoshanLiu** [comment]
specifically it is this code that returns false, causing it to think that master is not formatted

  private boolean isFormatted(String folder, String path) throws IOException {
    if (!folder.endsWith(TachyonURI.SEPARATOR)) {
      folder += TachyonURI.SEPARATOR;
    }
    UnderFileSystem ufs = UnderFileSystem.get(folder, mTachyonConf);
    String[] files = ufs.list(folder);
    if (files == null) {
      return false;
    }
    for (String file : files) {
      if (file.startsWith(path)) {
        return true;
      }
    }
    return false;
  }

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by haoyuan** [comment]
Any update on this?

**Comment by ShaoshanLiu** [comment]
will submit an update later today, but this change is more complicated than expected, currently working on making sure it passes all tests.

**Comment by ShaoshanLiu** [comment]
this is not ready yet, will send out another PR when this is fully tested.

**Pull request closed without merging**
