### PR TITLE
[TACHYON-1663]Add the Chinese version of documentation page 'HomePage'(index)

### PR DESCRIPTION
**Pull request by TeddyBear1314**
https://tachyon.atlassian.net/browse/TACHYON-1663

### CODE REVIEW

**Comment by gpang** [comment]
ok to test

**Comment by ifcharming** [comment]
Thank you for creating the Chinese version Homepage!
Overall looks great.
One question: is there a defined Chinese word for "lineage"? the technology used in Tachyon. 
"血统关系" sounds more like the general translation for "lineage" in anthropology...

**Comment by yupeng9** [comment]
I googled "Spark Lineage" and it seems most Chinese websites translated it into "血统".

**Comment by ifcharming** [comment]
LGTM

**Comment by yupeng9** [comment]
LGTM. Thanks for the doc contribution.

**Pull request merged**
