### PR TITLE
[TACHYON-1189] Declare mType in TachyonException as final

### PR DESCRIPTION
**Pull request by shuhuai007**
Please review
https://tachyon.atlassian.net/browse/TACHYON-1189
https://tachyon.atlassian.net/browse/TACHYON-1188
https://tachyon.atlassian.net/browse/TACHYON-1183

### CODE REVIEW

**Comment by yupeng9** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
ok to test.

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by yupeng9** [comment]
LGTM

**Comment by yupeng9** [comment]
Thanks for the improvement!

**Pull request merged**
