### PR TITLE
[WIP][TACHYON-868] Remote read should manage block locks by the stream

### PR DESCRIPTION
**Pull request by miasantreble**
https://tachyon.atlassian.net/browse/TACHYON-868

### CODE REVIEW

**Comment by miasantreble** [comment]
@calvinjia is this change what you were expecting? 
In the JIRA you said "instead of the remote reader", does that mean currently there is another lock managed by the remote reader? 
Do you mind pointing out where that is? I assume you were talking about NettyRemoteBlockReader and TCPRemoteBlockReader, right?

**Comment by calvinjia** [comment]
@miasantreble I think this approach would work, since the block lock acquired is a read lock and we just end up double locking the block (once by the remote stream and once by the data server). It would be good to clean up the code on the data server side though (for example see `DataServerHandler.java`)

**Comment by miasantreble** [comment]
@calvinjia thanks for the input! I checked `DataServerHandler.java`, looks like [`readBlockRemote`](https://github.com/amplab/tachyon/blob/master/servers/src/main/java/tachyon/worker/netty/DataServerHandler.java#L116) needs lockId to proceed . Shall I come up with another version of [`getBlockReader`](https://github.com/amplab/tachyon/blob/master/servers/src/main/java/tachyon/worker/block/TieredBlockStore.java#L167) that doesn't require a lockId? thanks!

**Comment by calvinjia** [comment]
@miasantreble Since this is a design type of a question, I've replied on the JIRA ticket.

**Comment by miasantreble** [comment]
since wip_master_client has been merged into master, closing this PR and will open a new PR towards master later

**Pull request closed without merging**
