### PR TITLE
[TACHYON-1638]Add the Chinese version of documentation page of 'Developer Tips'

### PR DESCRIPTION
**Pull request by summerDG**
Add the Chinese version of documentation page of 'Developer Tips'. See https://tachyon.atlassian.net/browse/TACHYON-1638

### CODE REVIEW

**Comment by ifcharming** [comment]
ok to test

**Comment by ifcharming** [comment]
LGTM

Thank you!

**Comment by summerDG** [comment]
Click http://www.tachyon-project.org/documentation/master/en/Developer-Tips.html and choose Chinese version.

**Comment by yupeng9** [comment]
LGTM

**Pull request merged**
