### PR TITLE
[TACHYON-1245] AccessBlock in LocalBlockInStream

### PR DESCRIPTION
**Pull request by Yours-shupeng**
[TACHYON-1245](https://tachyon.atlassian.net/browse/TACHYON-1245)
Call `accessBlock()` method in `LocalBlockInStream.java`

### CODE REVIEW

**Comment by Yours-shupeng** [comment]
@calvinjia Is it okay to call `accessBlock()` in the `close()` method of `LocalBlockInStream.java`?

**Comment by Yours-shupeng** [comment]
Jenkins, test this please

**Comment by uronce-cc** [comment]
Could you create a jira ticket to explain why we need to call `accessBlock()` in `LocalBlockInStream`? Does `RemoteBlockInStream` needs to call `accessBlock()` too? If not, why?  What will happen without calling it? Thanks.

**Comment by uronce-cc** [comment]
Before calling `accessBlock()`, we should verify something was read from the stream. There is a TODO on [this line](https://github.com/amplab/tachyon/pull/2004/files#diff-74a09a2b94653b30b33b0aa3e3969c90R93), you could also leave a TODO here, or better, take that TODO.

**Comment by Yours-shupeng** [comment]
@uronce-cc jira ticked is created in [TACHYON-1245](https://tachyon.atlassian.net/browse/TACHYON-1245)

**Comment by Yours-shupeng** [comment]
@uronce-cc I add a counter in `BufferedBlockInStream` to count the bytes already read.

**Comment by uronce-cc** [comment]
What about just having a boolean variable indicating whether some data is read?

**Comment by Yours-shupeng** [comment]
@uronce-cc It's reasonable. I have updated it.

**Comment by calvinjia** [comment]
LGTM

**Comment by apc999** [comment]
+1 LGTM

**Pull request merged**
