### PR TITLE
[TACHYON-935] Started to change self link in documentation to code in server module

### PR DESCRIPTION
**Pull request by HorizonNet**
https://tachyon.atlassian.net/browse/TACHYON-935

### CODE REVIEW

**Comment by apc999** [comment]
@HorizonNet  thanks for the patch. It seems by changing `{@link foo}` to `{@code foo}`,  `foo` will not be changed accordingly if it is refactored by an IDE.

**Comment by yupeng9** [comment]
@HorizonNet , @apc999 is right. At least Eclipse can only change `@link` upon refactoring.

**Comment by HorizonNet** [comment]
I'm using the points mentioned in https://github.com/amplab/tachyon/pull/2102. If you want we can change the third point to use ```@link``` instead of ```@code```.

**Comment by yupeng9** [comment]
Yeah, `@link` might be better, because when the class itself is renamed via IDE, the `@link` can be updated automatically.

**Comment by HorizonNet** [comment]
Alright, let me update the PR according to this.

**Comment by aaudiber** [comment]
@apc999 @yupeng9 @HorizonNet Does this mean we should always use `@link` and never use `@code`? What about point 1 of https://github.com/amplab/tachyon/pull/2102?

**Comment by HorizonNet** [comment]
@aaudiber As of today, we will use ```@link```  instead of ```@code``` throughout the documentation. There are some limitations from the IDEs to refactor a ```@code``` block. Nevertheless, I saw a few sections where ```@code``` would be the better choice (when it is a real code snippet).

**Comment by yupeng9** [comment]
Agree with @HorizonNet.

**Pull request closed without merging**
