### PR TITLE
[TACHYON-850] add a default ClientOptions constructor

### PR DESCRIPTION
**Pull request by miasantreble**
https://tachyon.atlassian.net/browse/TACHYON-850

### CODE REVIEW

**Comment by calvinjia** [comment]
@miasantreble I think we currently have a static method called `defaults`.

**Comment by miasantreble** [comment]
@calvinjia so do we still want a default constructor and have it call the `defaults` method?

**Comment by calvinjia** [comment]
@miasantreble I think its better to go through the builder (like how it is currently) this way we only need to have one place to set the defaults.

**Comment by miasantreble** [comment]
sure, I will close this PR and JIRA, thanks

**Pull request closed without merging**
