### PR TITLE
Revert "Added slaves file back since it was breaking bigtop rpm"

### PR DESCRIPTION
**Pull request by haoyuan**
Reverts amplab/tachyon#610

### CODE REVIEW

**Comment by dcapwell** [comment]
Why revert?

**Comment by haoyuan** [comment]
Because of the https://tachyon.atlassian.net/browse/TACHYON-213

@hsaputra  Am I mis-understanding something?

**Comment by dcapwell** [comment]
Henry asked you to revert but if you do you can not build the rpm against
master.  I currently rely on it so I get broken.

When a release finally happens we can revert this since we can update
bigtop then

**Comment by haoyuan** [comment]
Make sense. Let me change it back.

**Comment by dcapwell** [comment]
Thanks

**Comment by hsaputra** [comment]
Ugh, this is not perfect but I guess we need it to allow external clients
to generate RPM :(

**Comment by hsaputra** [comment]
No, Haoyuan you were right. David works in different project that requires
the slaves file to be there to build rpm.

I don't like having temporary file in master but since we don't release
often I guess we need to do this.

Sorry for the confusion HY :(

**Pull request merged**
