### PR TITLE
[TACHYON-464] Update dependencies of perf module

### PR DESCRIPTION
**Pull request by swatDong**
https://tachyon.atlassian.net/browse/TACHYON-464
The master branch modules are refactored that perf needs to update its dependencies.
Like #931 , manually to add the underfilesystem dependencies.

### CODE REVIEW

**Comment by apc999** [comment]
Could you update this PR with a JIRA number and link? In this way, we could better understand the context and keep track of the changes

Thanks

**Comment by calvinjia** [comment]
@swatDong Thanks for the patch! You may need to update the checkstyle conf since it seems to be picking up the thrift files in perf.

**Comment by swatDong** [comment]
@apc999 issue created https://tachyon.atlassian.net/browse/TACHYON-464

**Comment by swatDong** [comment]
@calvinjia I fixed the checkstyle conf of perf. PerfConf.java uses the early MasterConf/WorkerConf style and I just get around it.

**Comment by apc999** [comment]
LGTM . Thanks

**Comment by calvinjia** [comment]
+1 LGTM

**Pull request merged**
