### PR TITLE
[WIP] Add examples to keyvalue package

### PR DESCRIPTION
**Pull request by uronce-cc**
1. An example illustrating key-value store native API. Has been verified.
2. An example mapreduce job reading and writing to a key-value store. Stuck in testing on an EC2 hadoop1.2.1 cluster.

### CODE REVIEW

**Comment by uronce-cc** [comment]
I was blocked by this exception:
```
[ec2-user@TachyonMaster hadoop]$ ./bin/hadoop jar key-value.jar tachyon.examples.keyvalue.hadoop.CloneKeyValueStore tachyon://TachyonMaster:19998/kvstore tachyon://TachyonMaster:19998/kvstore-1
16/01/22 15:46:50 WARN mapred.JobClient: Use GenericOptionsParser for parsing the arguments. Applications should implement Tool for the same.
16/01/22 15:46:50 INFO : initialize(tachyon://TachyonMaster:19998/kvstore-1, Configuration: core-default.xml, core-site.xml, mapred-default.xml, mapred-site.xml, hdfs-default.xml, hdfs-site.xml). Connecting to Tachyon: tachyon://TachyonMaster:19998/kvstore-1
16/01/22 15:46:50 INFO : Loading Tachyon properties from Hadoop configuration: {}
16/01/22 15:46:50 INFO : Tachyon client (version 0.9.0-SNAPSHOT) is trying to connect with FileSystemMasterClient master @ TachyonMaster/172.31.25.186:19998
16/01/22 15:46:50 INFO : Client registered with FileSystemMasterClient master @ TachyonMaster/172.31.25.186:19998
16/01/22 15:46:51 INFO : tachyon://TachyonMaster:19998 tachyon://TachyonMaster:19998 hdfs://TachyonMaster:9000
16/01/22 15:46:51 INFO : getFileStatus(tachyon://TachyonMaster:19998/kvstore-1): HDFS Path: hdfs://TachyonMaster:9000/kvstore-1 Tachyon Path: tachyon://TachyonMaster:19998/kvstore-1
16/01/22 15:46:51 INFO : Tachyon client (version 0.9.0-SNAPSHOT) is trying to connect with KeyValueMasterClient master @ TachyonMaster/172.31.25.186:19998
16/01/22 15:46:51 INFO : Client registered with KeyValueMasterClient master @ TachyonMaster/172.31.25.186:19998
16/01/22 15:46:51 INFO mapred.JobClient: Cleaning up the staging area hdfs://TachyonMaster:9000/tmp/hadoop-tmpstore/mapred/staging/ec2-user/.staging/job_201601221440_0011
Exception in thread "main" java.lang.NoSuchMethodError: tachyon.thrift.KeyValueMasterClientService$Client: method <init>(Ltachyon/org/apache/thrift/protocol/TProtocol;)V not found
	at tachyon.client.keyvalue.KeyValueMasterClient.afterConnect(KeyValueMasterClient.java:71)
	at tachyon.ClientBase.connect(ClientBase.java:177)
	at tachyon.ClientBase.retryRPC(ClientBase.java:326)
	at tachyon.client.keyvalue.KeyValueMasterClient.getPartitionInfo(KeyValueMasterClient.java:138)
	at tachyon.client.keyvalue.hadoop.KeyValueInputFormat.getSplits(KeyValueInputFormat.java:68)
	at org.apache.hadoop.mapred.JobClient.writeOldSplits(JobClient.java:1081)
	at org.apache.hadoop.mapred.JobClient.writeSplits(JobClient.java:1073)
	at org.apache.hadoop.mapred.JobClient.access$700(JobClient.java:179)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:983)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:936)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
	at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:936)
	at org.apache.hadoop.mapred.JobClient.submitJob(JobClient.java:910)
	at org.apache.hadoop.mapred.JobClient.runJob(JobClient.java:1353)
	at tachyon.examples.keyvalue.hadoop.CloneKeyValueStore.main(CloneKeyValueStore.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:160)
```

**Comment by uronce-cc** [comment]
The `key-value.jar` is manually generated by
```
mkdir -p key-value-classes
for f in `find /tachyon -name "*.class"`; do cp $f key-value-classes; done
jar -cvf key-value.jar -C key-value-classes/ .
```

**Comment by uronce-cc** [comment]
Any help is appreciated!

**Comment by aaudiber** [comment]
It's looking for a constructor which takes a `tachyon/org/apache/thrift/protocol/TProtocol`, so this could be a shading issue (see the `tachyon/` prefix). Any ideas @apc999?

**Comment by apc999** [comment]
@aaudiber , yes it is looking for the shaded thrift classes, and this is not included. The key-value client jar should be put into classpath

In addition, I will submit a POM structure PR to have a cleaner solution.

**Comment by uronce-cc** [comment]
@aaudiber @apc999 Yeah, that's what I thought of, but `tachyon/thrift/KeyValueMasterClientService$Client.class` do exist only once in `key-value.jar`.

**Pull request closed without merging**
