### PR TITLE
Dummy under fs

### PR DESCRIPTION
**Pull request by ShaoshanLiu**
second batch of commits to enable Dummy UnderFS

### CODE REVIEW

**Comment by calvinjia** [comment]
Hmm is there any better way of doing this? Since every time we reference an underfs client we will need to wrap it in an `if (!dummyUFS)` block.

**Comment by ShaoshanLiu** [comment]
then I guess we need to make a smart dummy...hmm, let me look into it.

**Comment by calvinjia** [comment]
Thanks!
One thing I've been wondering is how the StorageDir will be handled.

**Comment by ShaoshanLiu** [comment]
Maybe I can do a DummyFileInputStream and DummyFileOutputStream and avoid all these changes, this should handle StorageDir as well. Let me check

**Pull request closed without merging**
